sonar.projectKey=thebtf_engram
sonar.projectName=Engram
sonar.sourceEncoding=UTF-8
sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.exclusions=**/*_test.go
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
