// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/engram/v1/engram.proto

package engramv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectEventType int32

const (
	ProjectEventType_PROJECT_EVENT_TYPE_UNSPECIFIED ProjectEventType = 0
	ProjectEventType_PROJECT_EVENT_TYPE_REMOVED     ProjectEventType = 1
	ProjectEventType_PROJECT_EVENT_TYPE_CREATED     ProjectEventType = 2 // reserved for v0.2.0
	ProjectEventType_PROJECT_EVENT_TYPE_RENAMED     ProjectEventType = 3 // reserved for v0.2.0
)

// Enum value maps for ProjectEventType.
var (
	ProjectEventType_name = map[int32]string{
		0: "PROJECT_EVENT_TYPE_UNSPECIFIED",
		1: "PROJECT_EVENT_TYPE_REMOVED",
		2: "PROJECT_EVENT_TYPE_CREATED",
		3: "PROJECT_EVENT_TYPE_RENAMED",
	}
	ProjectEventType_value = map[string]int32{
		"PROJECT_EVENT_TYPE_UNSPECIFIED": 0,
		"PROJECT_EVENT_TYPE_REMOVED":     1,
		"PROJECT_EVENT_TYPE_CREATED":     2,
		"PROJECT_EVENT_TYPE_RENAMED":     3,
	}
)

func (x ProjectEventType) Enum() *ProjectEventType {
	p := new(ProjectEventType)
	*p = x
	return p
}

func (x ProjectEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engram_v1_engram_proto_enumTypes[0].Descriptor()
}

func (ProjectEventType) Type() protoreflect.EnumType {
	return &file_proto_engram_v1_engram_proto_enumTypes[0]
}

func (x ProjectEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectEventType.Descriptor instead.
func (ProjectEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{0}
}

type SyncProjectStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_project_ids is the set of ProjectContext.ID values the daemon
	// currently tracks (one entry per connected CC session). Order is not
	// significant. Max 10 000 entries (server enforces the cap via
	// INVALID_ARGUMENT).
	LocalProjectIds []string `protobuf:"bytes,1,rep,name=local_project_ids,json=localProjectIds,proto3" json:"local_project_ids,omitempty"`
	// client_id uniquely identifies this daemon instance for audit logging.
	// Typically `${daemon_pid}-${daemon_start_unix}`.
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncProjectStateRequest) Reset() {
	*x = SyncProjectStateRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProjectStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProjectStateRequest) ProtoMessage() {}

func (x *SyncProjectStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProjectStateRequest.ProtoReflect.Descriptor instead.
func (*SyncProjectStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{0}
}

func (x *SyncProjectStateRequest) GetLocalProjectIds() []string {
	if x != nil {
		return x.LocalProjectIds
	}
	return nil
}

func (x *SyncProjectStateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SyncProjectStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// removed lists project IDs that the daemon has locally but the server
	// has no record of (removed_at IS NOT NULL or not in table). The daemon
	// fans these out to every registered ProjectRemovalAware module.
	Removed []string `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	// unknown lists project IDs that the server HAS a record of but that
	// look orphaned (last heartbeat > 24h ago AND removed_at IS NULL). The
	// daemon MAY log these for operator attention but does NOT fan them out
	// — only `removed` is authoritative.
	Unknown []string `protobuf:"bytes,2,rep,name=unknown,proto3" json:"unknown,omitempty"`
	// server_time_unix_ms is the server's wall clock at the time the
	// response was built. The daemon uses it for clock-skew detection.
	ServerTimeUnixMs int64 `protobuf:"varint,3,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncProjectStateResponse) Reset() {
	*x = SyncProjectStateResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProjectStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProjectStateResponse) ProtoMessage() {}

func (x *SyncProjectStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProjectStateResponse.ProtoReflect.Descriptor instead.
func (*SyncProjectStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{1}
}

func (x *SyncProjectStateResponse) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *SyncProjectStateResponse) GetUnknown() []string {
	if x != nil {
		return x.Unknown
	}
	return nil
}

func (x *SyncProjectStateResponse) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type ProjectEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id uniquely identifies this daemon instance for audit logging.
	// Same format as SyncProjectStateRequest.client_id.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// since_event_id allows the daemon to resume from a specific event after
	// reconnection. Empty string means "start from now; no replay".
	//
	// In v0.1.0 the server is NOT required to persist events for replay —
	// this field is reserved for forward compatibility. A v0.1.0 server
	// that receives a non-empty since_event_id MUST return OUT_OF_RANGE.
	SinceEventId  string `protobuf:"bytes,2,opt,name=since_event_id,json=sinceEventId,proto3" json:"since_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEventsRequest) Reset() {
	*x = ProjectEventsRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEventsRequest) ProtoMessage() {}

func (x *ProjectEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEventsRequest.ProtoReflect.Descriptor instead.
func (*ProjectEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectEventsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProjectEventsRequest) GetSinceEventId() string {
	if x != nil {
		return x.SinceEventId
	}
	return ""
}

type ProjectEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is a monotonically increasing server-side identifier for this
	// event. Opaque to the daemon; used only for since_event_id replay.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// event_type is the canonical event category. v0.1.0 only emits
	// PROJECT_EVENT_TYPE_REMOVED; the field is forward-compatible via the
	// ProjectEventType enum below.
	EventType ProjectEventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=engram.v1.ProjectEventType" json:"event_type,omitempty"`
	// project_id is the canonical muxcore ProjectContext.ID value.
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// timestamp_unix_ms is the server-side wall clock when the event was
	// generated.
	TimestampUnixMs int64 `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// reason is a free-form server-provided explanation (e.g. "dashboard
	// operator removed", "retention policy expired").
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// metadata is a key-value map for forward-compatible extension. v0.1.0
	// does NOT define any required keys.
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEvent) Reset() {
	*x = ProjectEvent{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEvent) ProtoMessage() {}

func (x *ProjectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEvent.ProtoReflect.Descriptor instead.
func (*ProjectEvent) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ProjectEvent) GetEventType() ProjectEventType {
	if x != nil {
		return x.EventType
	}
	return ProjectEventType_PROJECT_EVENT_TYPE_UNSPECIFIED
}

func (x *ProjectEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ProjectEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProjectEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CallToolRequest carries an MCP tool invocation.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MCP tool name (e.g., "store_memory", "recall", "search").
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON bytes (same as MCP JSON-RPC params.arguments).
	ArgumentsJson []byte `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Project identity for scope isolation (from git-derived slug).
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Claude session ID for tracking and outcome propagation.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{4}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *CallToolRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CallToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// CallToolResponse carries the result of an MCP tool call.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the tool returned an error result.
	IsError bool `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Tool result as JSON bytes (MCP content array serialized).
	ContentJson   []byte `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{5}
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *CallToolResponse) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

// InitializeRequest is the handshake from daemon to server.
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{6}
}

func (x *InitializeRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *InitializeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *InitializeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// InitializeResponse carries server capabilities and tool definitions.
type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{7}
}

func (x *InitializeResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *InitializeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *InitializeResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolDefinition describes a single MCP tool.
type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for the tool's input parameters.
	InputSchemaJson []byte `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{8}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{9}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{10}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_engram_v1_engram_proto protoreflect.FileDescriptor

const file_proto_engram_v1_engram_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/engram/v1/engram.proto\x12\tengram.v1\"b\n" +
	"\x17SyncProjectStateRequest\x12*\n" +
	"\x11local_project_ids\x18\x01 \x03(\tR\x0flocalProjectIds\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"}\n" +
	"\x18SyncProjectStateResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x03(\tR\aremoved\x12\x18\n" +
	"\aunknown\x18\x02 \x03(\tR\aunknown\x12-\n" +
	"\x13server_time_unix_ms\x18\x03 \x01(\x03R\x10serverTimeUnixMs\"Y\n" +
	"\x14ProjectEventsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12$\n" +
	"\x0esince_event_id\x18\x02 \x01(\tR\fsinceEventId\"\xc8\x02\n" +
	"\fProjectEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12:\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1b.engram.v1.ProjectEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.engram.v1.ProjectEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\fR\rargumentsJson\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"P\n" +
	"\x10CallToolResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\fR\vcontentJson\"u\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\"\x8d\x01\n" +
	"\x12InitializeResponse\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12/\n" +
	"\x05tools\x18\x03 \x03(\v2\x19.engram.v1.ToolDefinitionR\x05tools\"r\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\fR\x0finputSchemaJson\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*\x96\x01\n" +
	"\x10ProjectEventType\x12\"\n" +
	"\x1ePROJECT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_REMOVED\x10\x01\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_CREATED\x10\x02\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_RENAMED\x10\x032\x82\x03\n" +
	"\rEngramService\x12C\n" +
	"\bCallTool\x12\x1a.engram.v1.CallToolRequest\x1a\x1b.engram.v1.CallToolResponse\x12I\n" +
	"\n" +
	"Initialize\x12\x1c.engram.v1.InitializeRequest\x1a\x1d.engram.v1.InitializeResponse\x127\n" +
	"\x04Ping\x12\x16.engram.v1.PingRequest\x1a\x17.engram.v1.PingResponse\x12[\n" +
	"\x10SyncProjectState\x12\".engram.v1.SyncProjectStateRequest\x1a#.engram.v1.SyncProjectStateResponse\x12K\n" +
	"\rProjectEvents\x12\x1f.engram.v1.ProjectEventsRequest\x1a\x17.engram.v1.ProjectEvent0\x01B3Z1github.com/thebtf/engram/proto/engram/v1;engramv1b\x06proto3"

var (
	file_proto_engram_v1_engram_proto_rawDescOnce sync.Once
	file_proto_engram_v1_engram_proto_rawDescData []byte
)

func file_proto_engram_v1_engram_proto_rawDescGZIP() []byte {
	file_proto_engram_v1_engram_proto_rawDescOnce.Do(func() {
		file_proto_engram_v1_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)))
	})
	return file_proto_engram_v1_engram_proto_rawDescData
}

var file_proto_engram_v1_engram_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_engram_v1_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_engram_v1_engram_proto_goTypes = []any{
	(ProjectEventType)(0),            // 0: engram.v1.ProjectEventType
	(*SyncProjectStateRequest)(nil),  // 1: engram.v1.SyncProjectStateRequest
	(*SyncProjectStateResponse)(nil), // 2: engram.v1.SyncProjectStateResponse
	(*ProjectEventsRequest)(nil),     // 3: engram.v1.ProjectEventsRequest
	(*ProjectEvent)(nil),             // 4: engram.v1.ProjectEvent
	(*CallToolRequest)(nil),          // 5: engram.v1.CallToolRequest
	(*CallToolResponse)(nil),         // 6: engram.v1.CallToolResponse
	(*InitializeRequest)(nil),        // 7: engram.v1.InitializeRequest
	(*InitializeResponse)(nil),       // 8: engram.v1.InitializeResponse
	(*ToolDefinition)(nil),           // 9: engram.v1.ToolDefinition
	(*PingRequest)(nil),              // 10: engram.v1.PingRequest
	(*PingResponse)(nil),             // 11: engram.v1.PingResponse
	nil,                              // 12: engram.v1.ProjectEvent.MetadataEntry
}
var file_proto_engram_v1_engram_proto_depIdxs = []int32{
	0,  // 0: engram.v1.ProjectEvent.event_type:type_name -> engram.v1.ProjectEventType
	12, // 1: engram.v1.ProjectEvent.metadata:type_name -> engram.v1.ProjectEvent.MetadataEntry
	9,  // 2: engram.v1.InitializeResponse.tools:type_name -> engram.v1.ToolDefinition
	5,  // 3: engram.v1.EngramService.CallTool:input_type -> engram.v1.CallToolRequest
	7,  // 4: engram.v1.EngramService.Initialize:input_type -> engram.v1.InitializeRequest
	10, // 5: engram.v1.EngramService.Ping:input_type -> engram.v1.PingRequest
	1,  // 6: engram.v1.EngramService.SyncProjectState:input_type -> engram.v1.SyncProjectStateRequest
	3,  // 7: engram.v1.EngramService.ProjectEvents:input_type -> engram.v1.ProjectEventsRequest
	6,  // 8: engram.v1.EngramService.CallTool:output_type -> engram.v1.CallToolResponse
	8,  // 9: engram.v1.EngramService.Initialize:output_type -> engram.v1.InitializeResponse
	11, // 10: engram.v1.EngramService.Ping:output_type -> engram.v1.PingResponse
	2,  // 11: engram.v1.EngramService.SyncProjectState:output_type -> engram.v1.SyncProjectStateResponse
	4,  // 12: engram.v1.EngramService.ProjectEvents:output_type -> engram.v1.ProjectEvent
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_engram_v1_engram_proto_init() }
func file_proto_engram_v1_engram_proto_init() {
	if File_proto_engram_v1_engram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engram_v1_engram_proto_goTypes,
		DependencyIndexes: file_proto_engram_v1_engram_proto_depIdxs,
		EnumInfos:         file_proto_engram_v1_engram_proto_enumTypes,
		MessageInfos:      file_proto_engram_v1_engram_proto_msgTypes,
	}.Build()
	File_proto_engram_v1_engram_proto = out.File
	file_proto_engram_v1_engram_proto_goTypes = nil
	file_proto_engram_v1_engram_proto_depIdxs = nil
}
