// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/engram/v1/engram.proto

package engramv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectEventType int32

const (
	ProjectEventType_PROJECT_EVENT_TYPE_UNSPECIFIED ProjectEventType = 0
	ProjectEventType_PROJECT_EVENT_TYPE_REMOVED     ProjectEventType = 1
	ProjectEventType_PROJECT_EVENT_TYPE_CREATED     ProjectEventType = 2 // reserved for v0.2.0
	ProjectEventType_PROJECT_EVENT_TYPE_RENAMED     ProjectEventType = 3 // reserved for v0.2.0
)

// Enum value maps for ProjectEventType.
var (
	ProjectEventType_name = map[int32]string{
		0: "PROJECT_EVENT_TYPE_UNSPECIFIED",
		1: "PROJECT_EVENT_TYPE_REMOVED",
		2: "PROJECT_EVENT_TYPE_CREATED",
		3: "PROJECT_EVENT_TYPE_RENAMED",
	}
	ProjectEventType_value = map[string]int32{
		"PROJECT_EVENT_TYPE_UNSPECIFIED": 0,
		"PROJECT_EVENT_TYPE_REMOVED":     1,
		"PROJECT_EVENT_TYPE_CREATED":     2,
		"PROJECT_EVENT_TYPE_RENAMED":     3,
	}
)

func (x ProjectEventType) Enum() *ProjectEventType {
	p := new(ProjectEventType)
	*p = x
	return p
}

func (x ProjectEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engram_v1_engram_proto_enumTypes[0].Descriptor()
}

func (ProjectEventType) Type() protoreflect.EnumType {
	return &file_proto_engram_v1_engram_proto_enumTypes[0]
}

func (x ProjectEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectEventType.Descriptor instead.
func (ProjectEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{0}
}

type SyncProjectStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_project_ids is the set of ProjectContext.ID values the daemon
	// currently tracks (one entry per connected CC session). Order is not
	// significant. Max 10 000 entries (server enforces the cap via
	// INVALID_ARGUMENT).
	LocalProjectIds []string `protobuf:"bytes,1,rep,name=local_project_ids,json=localProjectIds,proto3" json:"local_project_ids,omitempty"`
	// client_id uniquely identifies this daemon instance for audit logging.
	// Typically `${daemon_pid}-${daemon_start_unix}`.
	ClientId      string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncProjectStateRequest) Reset() {
	*x = SyncProjectStateRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProjectStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProjectStateRequest) ProtoMessage() {}

func (x *SyncProjectStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProjectStateRequest.ProtoReflect.Descriptor instead.
func (*SyncProjectStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{0}
}

func (x *SyncProjectStateRequest) GetLocalProjectIds() []string {
	if x != nil {
		return x.LocalProjectIds
	}
	return nil
}

func (x *SyncProjectStateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SyncProjectStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// removed lists project IDs that the daemon has locally but the server
	// has no record of (removed_at IS NOT NULL or not in table). The daemon
	// fans these out to every registered ProjectRemovalAware module.
	Removed []string `protobuf:"bytes,1,rep,name=removed,proto3" json:"removed,omitempty"`
	// unknown lists project IDs that the server HAS a record of but that
	// look orphaned (last heartbeat > 24h ago AND removed_at IS NULL). The
	// daemon MAY log these for operator attention but does NOT fan them out
	// — only `removed` is authoritative.
	Unknown []string `protobuf:"bytes,2,rep,name=unknown,proto3" json:"unknown,omitempty"`
	// server_time_unix_ms is the server's wall clock at the time the
	// response was built. The daemon uses it for clock-skew detection.
	ServerTimeUnixMs int64 `protobuf:"varint,3,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncProjectStateResponse) Reset() {
	*x = SyncProjectStateResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProjectStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProjectStateResponse) ProtoMessage() {}

func (x *SyncProjectStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProjectStateResponse.ProtoReflect.Descriptor instead.
func (*SyncProjectStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{1}
}

func (x *SyncProjectStateResponse) GetRemoved() []string {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *SyncProjectStateResponse) GetUnknown() []string {
	if x != nil {
		return x.Unknown
	}
	return nil
}

func (x *SyncProjectStateResponse) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

type ProjectEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_id uniquely identifies this daemon instance for audit logging.
	// Same format as SyncProjectStateRequest.client_id.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// since_event_id allows the daemon to resume from a specific event after
	// reconnection. Empty string means "start from now; no replay".
	//
	// In v0.1.0 the server is NOT required to persist events for replay —
	// this field is reserved for forward compatibility. A v0.1.0 server
	// that receives a non-empty since_event_id MUST return OUT_OF_RANGE.
	SinceEventId  string `protobuf:"bytes,2,opt,name=since_event_id,json=sinceEventId,proto3" json:"since_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEventsRequest) Reset() {
	*x = ProjectEventsRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEventsRequest) ProtoMessage() {}

func (x *ProjectEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEventsRequest.ProtoReflect.Descriptor instead.
func (*ProjectEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectEventsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProjectEventsRequest) GetSinceEventId() string {
	if x != nil {
		return x.SinceEventId
	}
	return ""
}

type ProjectEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_id is a monotonically increasing server-side identifier for this
	// event. Opaque to the daemon; used only for since_event_id replay.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// event_type is the canonical event category. v0.1.0 only emits
	// PROJECT_EVENT_TYPE_REMOVED; the field is forward-compatible via the
	// ProjectEventType enum below.
	EventType ProjectEventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=engram.v1.ProjectEventType" json:"event_type,omitempty"`
	// project_id is the canonical muxcore ProjectContext.ID value.
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// timestamp_unix_ms is the server-side wall clock when the event was
	// generated.
	TimestampUnixMs int64 `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// reason is a free-form server-provided explanation (e.g. "dashboard
	// operator removed", "retention policy expired").
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	// metadata is a key-value map for forward-compatible extension. v0.1.0
	// does NOT define any required keys.
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEvent) Reset() {
	*x = ProjectEvent{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEvent) ProtoMessage() {}

func (x *ProjectEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEvent.ProtoReflect.Descriptor instead.
func (*ProjectEvent) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ProjectEvent) GetEventType() ProjectEventType {
	if x != nil {
		return x.EventType
	}
	return ProjectEventType_PROJECT_EVENT_TYPE_UNSPECIFIED
}

func (x *ProjectEvent) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ProjectEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProjectEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetSessionStartContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project is the target project slug used to fetch static context entities.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// memories_limit is the maximum number of memories to return, ordered by newest first.
	// Zero means the server default.
	MemoriesLimit int32 `protobuf:"varint,2,opt,name=memories_limit,json=memoriesLimit,proto3" json:"memories_limit,omitempty"`
	// issues_limit is the maximum number of active issues to return, ordered by priority then newest first.
	// Zero means the server default.
	IssuesLimit   int32 `protobuf:"varint,3,opt,name=issues_limit,json=issuesLimit,proto3" json:"issues_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStartContextRequest) Reset() {
	*x = GetSessionStartContextRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStartContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStartContextRequest) ProtoMessage() {}

func (x *GetSessionStartContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStartContextRequest.ProtoReflect.Descriptor instead.
func (*GetSessionStartContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionStartContextRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetSessionStartContextRequest) GetMemoriesLimit() int32 {
	if x != nil {
		return x.MemoriesLimit
	}
	return 0
}

func (x *GetSessionStartContextRequest) GetIssuesLimit() int32 {
	if x != nil {
		return x.IssuesLimit
	}
	return 0
}

type GetSessionStartContextResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Issues        []*SessionStartIssue     `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Rules         []*SessionStartRule      `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	Memories      []*SessionStartMemory    `protobuf:"bytes,3,rep,name=memories,proto3" json:"memories,omitempty"`
	GeneratedAt   *timestamppb.Timestamp   `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	RuleRouter    *SessionStartRuleRouter  `protobuf:"bytes,5,opt,name=rule_router,json=ruleRouter,proto3" json:"rule_router,omitempty"`
	MetaSummary   *SessionStartMetaSummary `protobuf:"bytes,6,opt,name=meta_summary,json=metaSummary,proto3" json:"meta_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionStartContextResponse) Reset() {
	*x = GetSessionStartContextResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionStartContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionStartContextResponse) ProtoMessage() {}

func (x *GetSessionStartContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionStartContextResponse.ProtoReflect.Descriptor instead.
func (*GetSessionStartContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionStartContextResponse) GetIssues() []*SessionStartIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *GetSessionStartContextResponse) GetRules() []*SessionStartRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *GetSessionStartContextResponse) GetMemories() []*SessionStartMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *GetSessionStartContextResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetSessionStartContextResponse) GetRuleRouter() *SessionStartRuleRouter {
	if x != nil {
		return x.RuleRouter
	}
	return nil
}

func (x *GetSessionStartContextResponse) GetMetaSummary() *SessionStartMetaSummary {
	if x != nil {
		return x.MetaSummary
	}
	return nil
}

type SessionStartIssue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Priority       string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Type           string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	SourceProject  string                 `protobuf:"bytes,7,opt,name=source_project,json=sourceProject,proto3" json:"source_project,omitempty"`
	TargetProject  string                 `protobuf:"bytes,8,opt,name=target_project,json=targetProject,proto3" json:"target_project,omitempty"`
	SourceAgent    string                 `protobuf:"bytes,9,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	Labels         []string               `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	CommentCount   int64                  `protobuf:"varint,11,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	AcknowledgedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=acknowledged_at,json=acknowledgedAt,proto3" json:"acknowledged_at,omitempty"`
	ResolvedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	ReopenedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=reopened_at,json=reopenedAt,proto3" json:"reopened_at,omitempty"`
	ClosedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionStartIssue) Reset() {
	*x = SessionStartIssue{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartIssue) ProtoMessage() {}

func (x *SessionStartIssue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartIssue.ProtoReflect.Descriptor instead.
func (*SessionStartIssue) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{6}
}

func (x *SessionStartIssue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionStartIssue) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SessionStartIssue) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SessionStartIssue) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionStartIssue) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *SessionStartIssue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SessionStartIssue) GetSourceProject() string {
	if x != nil {
		return x.SourceProject
	}
	return ""
}

func (x *SessionStartIssue) GetTargetProject() string {
	if x != nil {
		return x.TargetProject
	}
	return ""
}

func (x *SessionStartIssue) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *SessionStartIssue) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SessionStartIssue) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *SessionStartIssue) GetAcknowledgedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcknowledgedAt
	}
	return nil
}

func (x *SessionStartIssue) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *SessionStartIssue) GetReopenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReopenedAt
	}
	return nil
}

func (x *SessionStartIssue) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *SessionStartIssue) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionStartIssue) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SessionStartRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	EditedBy      string                 `protobuf:"bytes,4,opt,name=edited_by,json=editedBy,proto3" json:"edited_by,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartRule) Reset() {
	*x = SessionStartRule{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRule) ProtoMessage() {}

func (x *SessionStartRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRule.ProtoReflect.Descriptor instead.
func (*SessionStartRule) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStartRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionStartRule) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionStartRule) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionStartRule) GetEditedBy() string {
	if x != nil {
		return x.EditedBy
	}
	return ""
}

func (x *SessionStartRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SessionStartRule) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SessionStartRule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionStartRule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SessionStartRuleRouter struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Enabled         bool                      `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Mode            string                    `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	KernelCount     int32                     `protobuf:"varint,3,opt,name=kernel_count,json=kernelCount,proto3" json:"kernel_count,omitempty"`
	ContextualCount int32                     `protobuf:"varint,4,opt,name=contextual_count,json=contextualCount,proto3" json:"contextual_count,omitempty"`
	SuppressedCount int32                     `protobuf:"varint,5,opt,name=suppressed_count,json=suppressedCount,proto3" json:"suppressed_count,omitempty"`
	BudgetOutcome   string                    `protobuf:"bytes,6,opt,name=budget_outcome,json=budgetOutcome,proto3" json:"budget_outcome,omitempty"`
	Kernel          []*SessionStartRulePacket `protobuf:"bytes,7,rep,name=kernel,proto3" json:"kernel,omitempty"`
	Contextual      []*SessionStartRulePacket `protobuf:"bytes,8,rep,name=contextual,proto3" json:"contextual,omitempty"`
	Suppressed      []*SessionStartRulePacket `protobuf:"bytes,9,rep,name=suppressed,proto3" json:"suppressed,omitempty"`
	FallbackReason  string                    `protobuf:"bytes,10,opt,name=fallback_reason,json=fallbackReason,proto3" json:"fallback_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionStartRuleRouter) Reset() {
	*x = SessionStartRuleRouter{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartRuleRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRuleRouter) ProtoMessage() {}

func (x *SessionStartRuleRouter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRuleRouter.ProtoReflect.Descriptor instead.
func (*SessionStartRuleRouter) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{8}
}

func (x *SessionStartRuleRouter) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SessionStartRuleRouter) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionStartRuleRouter) GetKernelCount() int32 {
	if x != nil {
		return x.KernelCount
	}
	return 0
}

func (x *SessionStartRuleRouter) GetContextualCount() int32 {
	if x != nil {
		return x.ContextualCount
	}
	return 0
}

func (x *SessionStartRuleRouter) GetSuppressedCount() int32 {
	if x != nil {
		return x.SuppressedCount
	}
	return 0
}

func (x *SessionStartRuleRouter) GetBudgetOutcome() string {
	if x != nil {
		return x.BudgetOutcome
	}
	return ""
}

func (x *SessionStartRuleRouter) GetKernel() []*SessionStartRulePacket {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *SessionStartRuleRouter) GetContextual() []*SessionStartRulePacket {
	if x != nil {
		return x.Contextual
	}
	return nil
}

func (x *SessionStartRuleRouter) GetSuppressed() []*SessionStartRulePacket {
	if x != nil {
		return x.Suppressed
	}
	return nil
}

func (x *SessionStartRuleRouter) GetFallbackReason() string {
	if x != nil {
		return x.FallbackReason
	}
	return ""
}

type SessionStartRulePacket struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RuleVersionId          int64                  `protobuf:"varint,1,opt,name=rule_version_id,json=ruleVersionId,proto3" json:"rule_version_id,omitempty"`
	LegacyBehavioralRuleId int64                  `protobuf:"varint,2,opt,name=legacy_behavioral_rule_id,json=legacyBehavioralRuleId,proto3" json:"legacy_behavioral_rule_id,omitempty"`
	Bucket                 string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Scope                  string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Audience               string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	Content                string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Summary                string                 `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	EvidenceHandles        []string               `protobuf:"bytes,8,rep,name=evidence_handles,json=evidenceHandles,proto3" json:"evidence_handles,omitempty"`
	State                  string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	BudgetClass            string                 `protobuf:"bytes,10,opt,name=budget_class,json=budgetClass,proto3" json:"budget_class,omitempty"`
	Priority               int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`
	SuppressionReason      string                 `protobuf:"bytes,12,opt,name=suppression_reason,json=suppressionReason,proto3" json:"suppression_reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SessionStartRulePacket) Reset() {
	*x = SessionStartRulePacket{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartRulePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartRulePacket) ProtoMessage() {}

func (x *SessionStartRulePacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartRulePacket.ProtoReflect.Descriptor instead.
func (*SessionStartRulePacket) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{9}
}

func (x *SessionStartRulePacket) GetRuleVersionId() int64 {
	if x != nil {
		return x.RuleVersionId
	}
	return 0
}

func (x *SessionStartRulePacket) GetLegacyBehavioralRuleId() int64 {
	if x != nil {
		return x.LegacyBehavioralRuleId
	}
	return 0
}

func (x *SessionStartRulePacket) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *SessionStartRulePacket) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SessionStartRulePacket) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *SessionStartRulePacket) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionStartRulePacket) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SessionStartRulePacket) GetEvidenceHandles() []string {
	if x != nil {
		return x.EvidenceHandles
	}
	return nil
}

func (x *SessionStartRulePacket) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionStartRulePacket) GetBudgetClass() string {
	if x != nil {
		return x.BudgetClass
	}
	return ""
}

func (x *SessionStartRulePacket) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SessionStartRulePacket) GetSuppressionReason() string {
	if x != nil {
		return x.SuppressionReason
	}
	return ""
}

type SessionStartMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	SourceAgent   string                 `protobuf:"bytes,5,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	EditedBy      string                 `protobuf:"bytes,6,opt,name=edited_by,json=editedBy,proto3" json:"edited_by,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartMemory) Reset() {
	*x = SessionStartMemory{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartMemory) ProtoMessage() {}

func (x *SessionStartMemory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartMemory.ProtoReflect.Descriptor instead.
func (*SessionStartMemory) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{10}
}

func (x *SessionStartMemory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SessionStartMemory) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionStartMemory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionStartMemory) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SessionStartMemory) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *SessionStartMemory) GetEditedBy() string {
	if x != nil {
		return x.EditedBy
	}
	return ""
}

func (x *SessionStartMemory) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SessionStartMemory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SessionStartMemory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SessionStartMetaTagCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStartMetaTagCount) Reset() {
	*x = SessionStartMetaTagCount{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartMetaTagCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartMetaTagCount) ProtoMessage() {}

func (x *SessionStartMetaTagCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartMetaTagCount.ProtoReflect.Descriptor instead.
func (*SessionStartMetaTagCount) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{11}
}

func (x *SessionStartMetaTagCount) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *SessionStartMetaTagCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SessionStartMetaSummary struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	Project         string                      `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	TotalCount      int64                       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TopTags         []*SessionStartMetaTagCount `protobuf:"bytes,3,rep,name=top_tags,json=topTags,proto3" json:"top_tags,omitempty"`
	OldestCreatedAt *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=oldest_created_at,json=oldestCreatedAt,proto3" json:"oldest_created_at,omitempty"`
	NewestCreatedAt *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=newest_created_at,json=newestCreatedAt,proto3" json:"newest_created_at,omitempty"`
	GeneratedAt     *timestamppb.Timestamp      `protobuf:"bytes,6,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionStartMetaSummary) Reset() {
	*x = SessionStartMetaSummary{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartMetaSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartMetaSummary) ProtoMessage() {}

func (x *SessionStartMetaSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartMetaSummary.ProtoReflect.Descriptor instead.
func (*SessionStartMetaSummary) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{12}
}

func (x *SessionStartMetaSummary) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionStartMetaSummary) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SessionStartMetaSummary) GetTopTags() []*SessionStartMetaTagCount {
	if x != nil {
		return x.TopTags
	}
	return nil
}

func (x *SessionStartMetaSummary) GetOldestCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestCreatedAt
	}
	return nil
}

func (x *SessionStartMetaSummary) GetNewestCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NewestCreatedAt
	}
	return nil
}

func (x *SessionStartMetaSummary) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type NegotiateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NegotiateVersionRequest) Reset() {
	*x = NegotiateVersionRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateVersionRequest) ProtoMessage() {}

func (x *NegotiateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateVersionRequest.ProtoReflect.Descriptor instead.
func (*NegotiateVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{13}
}

func (x *NegotiateVersionRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type NegotiateVersionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Compatible     bool                   `protobuf:"varint,1,opt,name=compatible,proto3" json:"compatible,omitempty"`
	ServerVersion  string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	IncompatReason string                 `protobuf:"bytes,3,opt,name=incompat_reason,json=incompatReason,proto3" json:"incompat_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NegotiateVersionResponse) Reset() {
	*x = NegotiateVersionResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiateVersionResponse) ProtoMessage() {}

func (x *NegotiateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiateVersionResponse.ProtoReflect.Descriptor instead.
func (*NegotiateVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{14}
}

func (x *NegotiateVersionResponse) GetCompatible() bool {
	if x != nil {
		return x.Compatible
	}
	return false
}

func (x *NegotiateVersionResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *NegotiateVersionResponse) GetIncompatReason() string {
	if x != nil {
		return x.IncompatReason
	}
	return ""
}

// CallToolRequest carries an MCP tool invocation.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MCP tool name (e.g., "store_memory", "recall", "search").
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON bytes (same as MCP JSON-RPC params.arguments).
	ArgumentsJson []byte `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Project identity for scope isolation (from git-derived slug).
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Claude session ID for tracking and outcome propagation.
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Full versioned identity metadata. Additive: old servers ignore it.
	ProjectIdentity *ProjectIdentityV2 `protobuf:"bytes,5,opt,name=project_identity,json=projectIdentity,proto3" json:"project_identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{15}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *CallToolRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CallToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallToolRequest) GetProjectIdentity() *ProjectIdentityV2 {
	if x != nil {
		return x.ProjectIdentity
	}
	return nil
}

// CallToolResponse carries the result of an MCP tool call.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the tool returned an error result.
	IsError bool `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Tool result as JSON bytes (MCP content array serialized).
	ContentJson []byte `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	// Server-resolved canonical selector used for this call.
	CanonicalProject string `protobuf:"bytes,3,opt,name=canonical_project,json=canonicalProject,proto3" json:"canonical_project,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{16}
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *CallToolResponse) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

func (x *CallToolResponse) GetCanonicalProject() string {
	if x != nil {
		return x.CanonicalProject
	}
	return ""
}

// InitializeRequest is the handshake from daemon to server.
type InitializeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientName      string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion   string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Project         string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	ProjectIdentity *ProjectIdentityV2     `protobuf:"bytes,4,opt,name=project_identity,json=projectIdentity,proto3" json:"project_identity,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{17}
}

func (x *InitializeRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *InitializeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *InitializeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *InitializeRequest) GetProjectIdentity() *ProjectIdentityV2 {
	if x != nil {
		return x.ProjectIdentity
	}
	return nil
}

// InitializeResponse carries server capabilities and tool definitions.
type InitializeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerName       string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Tools            []*ToolDefinition      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	CanonicalProject string                 `protobuf:"bytes,4,opt,name=canonical_project,json=canonicalProject,proto3" json:"canonical_project,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{18}
}

func (x *InitializeResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *InitializeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *InitializeResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *InitializeResponse) GetCanonicalProject() string {
	if x != nil {
		return x.CanonicalProject
	}
	return ""
}

// ToolDefinition describes a single MCP tool.
type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for the tool's input parameters.
	InputSchemaJson []byte `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{19}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{20}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{21}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// CodeChunkMeta carries the lightweight metadata for a single code chunk.
// chunk_type is a free-form string; the only value produced by CR-002a is
// "line-block". AST-derived types are added in CR-002b.
type CodeChunkMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ByteStart     int32                  `protobuf:"varint,3,opt,name=byte_start,json=byteStart,proto3" json:"byte_start,omitempty"`
	ByteEnd       int32                  `protobuf:"varint,4,opt,name=byte_end,json=byteEnd,proto3" json:"byte_end,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	ChunkType     string                 `protobuf:"bytes,6,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"`
	ContentSha256 string                 `protobuf:"bytes,7,opt,name=content_sha256,json=contentSha256,proto3" json:"content_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeChunkMeta) Reset() {
	*x = CodeChunkMeta{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeChunkMeta) ProtoMessage() {}

func (x *CodeChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeChunkMeta.ProtoReflect.Descriptor instead.
func (*CodeChunkMeta) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{22}
}

func (x *CodeChunkMeta) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *CodeChunkMeta) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CodeChunkMeta) GetByteStart() int32 {
	if x != nil {
		return x.ByteStart
	}
	return 0
}

func (x *CodeChunkMeta) GetByteEnd() int32 {
	if x != nil {
		return x.ByteEnd
	}
	return 0
}

func (x *CodeChunkMeta) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CodeChunkMeta) GetChunkType() string {
	if x != nil {
		return x.ChunkType
	}
	return ""
}

func (x *CodeChunkMeta) GetContentSha256() string {
	if x != nil {
		return x.ContentSha256
	}
	return ""
}

// CodeIndexNegotiateRequest carries the client's full chunk manifest for a
// project. The server diffs this against its stored identity keys and returns
// the delta (need_chunks / stale_chunks).
type CodeIndexNegotiateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IndexSessionId string                 `protobuf:"bytes,2,opt,name=index_session_id,json=indexSessionId,proto3" json:"index_session_id,omitempty"`
	Manifest       []*CodeChunkMeta       `protobuf:"bytes,3,rep,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeIndexNegotiateRequest) Reset() {
	*x = CodeIndexNegotiateRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeIndexNegotiateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeIndexNegotiateRequest) ProtoMessage() {}

func (x *CodeIndexNegotiateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeIndexNegotiateRequest.ProtoReflect.Descriptor instead.
func (*CodeIndexNegotiateRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{23}
}

func (x *CodeIndexNegotiateRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CodeIndexNegotiateRequest) GetIndexSessionId() string {
	if x != nil {
		return x.IndexSessionId
	}
	return ""
}

func (x *CodeIndexNegotiateRequest) GetManifest() []*CodeChunkMeta {
	if x != nil {
		return x.Manifest
	}
	return nil
}

// CodeIndexNegotiateResponse tells the client which chunks to upload and
// which server-side chunks are now stale.
//
//	need_chunks  — chunk_ids the server does not have (must be uploaded).
//	stale_chunks — chunk_ids present on the server but absent from the
//	               client manifest (will be swept at CodeIndexUpload EOF).
type CodeIndexNegotiateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NeedChunks    []string               `protobuf:"bytes,1,rep,name=need_chunks,json=needChunks,proto3" json:"need_chunks,omitempty"`
	StaleChunks   []string               `protobuf:"bytes,2,rep,name=stale_chunks,json=staleChunks,proto3" json:"stale_chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeIndexNegotiateResponse) Reset() {
	*x = CodeIndexNegotiateResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeIndexNegotiateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeIndexNegotiateResponse) ProtoMessage() {}

func (x *CodeIndexNegotiateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeIndexNegotiateResponse.ProtoReflect.Descriptor instead.
func (*CodeIndexNegotiateResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{24}
}

func (x *CodeIndexNegotiateResponse) GetNeedChunks() []string {
	if x != nil {
		return x.NeedChunks
	}
	return nil
}

func (x *CodeIndexNegotiateResponse) GetStaleChunks() []string {
	if x != nil {
		return x.StaleChunks
	}
	return nil
}

// CodeChunkUpload carries a single chunk payload in the CodeIndexUpload stream.
type CodeChunkUpload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProjectId      string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IndexSessionId string                 `protobuf:"bytes,2,opt,name=index_session_id,json=indexSessionId,proto3" json:"index_session_id,omitempty"`
	Meta           *CodeChunkMeta         `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	Content        []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CodeChunkUpload) Reset() {
	*x = CodeChunkUpload{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeChunkUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeChunkUpload) ProtoMessage() {}

func (x *CodeChunkUpload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeChunkUpload.ProtoReflect.Descriptor instead.
func (*CodeChunkUpload) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{25}
}

func (x *CodeChunkUpload) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CodeChunkUpload) GetIndexSessionId() string {
	if x != nil {
		return x.IndexSessionId
	}
	return ""
}

func (x *CodeChunkUpload) GetMeta() *CodeChunkMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *CodeChunkUpload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// CodeIndexUploadReceipt is returned when the CodeIndexUpload stream closes.
//
//	embedded — number of chunks successfully upserted.
//	deleted  — number of stale rows swept after stream close.
//	errors   — per-chunk error strings (non-fatal; successful chunks still count).
type CodeIndexUploadReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedded      int32                  `protobuf:"varint,1,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Deleted       int32                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeIndexUploadReceipt) Reset() {
	*x = CodeIndexUploadReceipt{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeIndexUploadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeIndexUploadReceipt) ProtoMessage() {}

func (x *CodeIndexUploadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeIndexUploadReceipt.ProtoReflect.Descriptor instead.
func (*CodeIndexUploadReceipt) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{26}
}

func (x *CodeIndexUploadReceipt) GetEmbedded() int32 {
	if x != nil {
		return x.Embedded
	}
	return 0
}

func (x *CodeIndexUploadReceipt) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *CodeIndexUploadReceipt) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// ProjectIdentityV2 carries one complete identity source. Git identities use
// git_remote+relative_path. Non-git identities use a 128-bit anchor and require
// explicit anchor_shared presence. The selector remains on the outer request
// for old-server compatibility; metadata is not an authentication credential.
// Appended after the existing message declarations to minimize generated-code
// churn while preserving every pre-v2 descriptor index.
type ProjectIdentityV2 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LegacyProjectId string                 `protobuf:"bytes,2,opt,name=legacy_project_id,json=legacyProjectId,proto3" json:"legacy_project_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	GitRemote       string                 `protobuf:"bytes,4,opt,name=git_remote,json=gitRemote,proto3" json:"git_remote,omitempty"`
	RelativePath    string                 `protobuf:"bytes,5,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	NonGitAnchor    string                 `protobuf:"bytes,6,opt,name=non_git_anchor,json=nonGitAnchor,proto3" json:"non_git_anchor,omitempty"`
	AnchorShared    *bool                  `protobuf:"varint,7,opt,name=anchor_shared,json=anchorShared,proto3,oneof" json:"anchor_shared,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectIdentityV2) Reset() {
	*x = ProjectIdentityV2{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectIdentityV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectIdentityV2) ProtoMessage() {}

func (x *ProjectIdentityV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectIdentityV2.ProtoReflect.Descriptor instead.
func (*ProjectIdentityV2) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{27}
}

func (x *ProjectIdentityV2) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProjectIdentityV2) GetLegacyProjectId() string {
	if x != nil {
		return x.LegacyProjectId
	}
	return ""
}

func (x *ProjectIdentityV2) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProjectIdentityV2) GetGitRemote() string {
	if x != nil {
		return x.GitRemote
	}
	return ""
}

func (x *ProjectIdentityV2) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *ProjectIdentityV2) GetNonGitAnchor() string {
	if x != nil {
		return x.NonGitAnchor
	}
	return ""
}

func (x *ProjectIdentityV2) GetAnchorShared() bool {
	if x != nil && x.AnchorShared != nil {
		return *x.AnchorShared
	}
	return false
}

var File_proto_engram_v1_engram_proto protoreflect.FileDescriptor

const file_proto_engram_v1_engram_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/engram/v1/engram.proto\x12\tengram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x17SyncProjectStateRequest\x12*\n" +
	"\x11local_project_ids\x18\x01 \x03(\tR\x0flocalProjectIds\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"}\n" +
	"\x18SyncProjectStateResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x03(\tR\aremoved\x12\x18\n" +
	"\aunknown\x18\x02 \x03(\tR\aunknown\x12-\n" +
	"\x13server_time_unix_ms\x18\x03 \x01(\x03R\x10serverTimeUnixMs\"Y\n" +
	"\x14ProjectEventsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12$\n" +
	"\x0esince_event_id\x18\x02 \x01(\tR\fsinceEventId\"\xc8\x02\n" +
	"\fProjectEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12:\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1b.engram.v1.ProjectEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.engram.v1.ProjectEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\x1dGetSessionStartContextRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12%\n" +
	"\x0ememories_limit\x18\x02 \x01(\x05R\rmemoriesLimit\x12!\n" +
	"\fissues_limit\x18\x03 \x01(\x05R\vissuesLimit\"\x8e\x03\n" +
	"\x1eGetSessionStartContextResponse\x124\n" +
	"\x06issues\x18\x01 \x03(\v2\x1c.engram.v1.SessionStartIssueR\x06issues\x121\n" +
	"\x05rules\x18\x02 \x03(\v2\x1b.engram.v1.SessionStartRuleR\x05rules\x129\n" +
	"\bmemories\x18\x03 \x03(\v2\x1d.engram.v1.SessionStartMemoryR\bmemories\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12B\n" +
	"\vrule_router\x18\x05 \x01(\v2!.engram.v1.SessionStartRuleRouterR\n" +
	"ruleRouter\x12E\n" +
	"\fmeta_summary\x18\x06 \x01(\v2\".engram.v1.SessionStartMetaSummaryR\vmetaSummary\"\xb1\x05\n" +
	"\x11SessionStartIssue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12%\n" +
	"\x0esource_project\x18\a \x01(\tR\rsourceProject\x12%\n" +
	"\x0etarget_project\x18\b \x01(\tR\rtargetProject\x12!\n" +
	"\fsource_agent\x18\t \x01(\tR\vsourceAgent\x12\x16\n" +
	"\x06labels\x18\n" +
	" \x03(\tR\x06labels\x12#\n" +
	"\rcomment_count\x18\v \x01(\x03R\fcommentCount\x12C\n" +
	"\x0facknowledged_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0eacknowledgedAt\x12;\n" +
	"\vresolved_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x12;\n" +
	"\vreopened_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reopenedAt\x127\n" +
	"\tclosed_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x02\n" +
	"\x10SessionStartRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tedited_by\x18\x04 \x01(\tR\beditedBy\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd0\x03\n" +
	"\x16SessionStartRuleRouter\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12!\n" +
	"\fkernel_count\x18\x03 \x01(\x05R\vkernelCount\x12)\n" +
	"\x10contextual_count\x18\x04 \x01(\x05R\x0fcontextualCount\x12)\n" +
	"\x10suppressed_count\x18\x05 \x01(\x05R\x0fsuppressedCount\x12%\n" +
	"\x0ebudget_outcome\x18\x06 \x01(\tR\rbudgetOutcome\x129\n" +
	"\x06kernel\x18\a \x03(\v2!.engram.v1.SessionStartRulePacketR\x06kernel\x12A\n" +
	"\n" +
	"contextual\x18\b \x03(\v2!.engram.v1.SessionStartRulePacketR\n" +
	"contextual\x12A\n" +
	"\n" +
	"suppressed\x18\t \x03(\v2!.engram.v1.SessionStartRulePacketR\n" +
	"suppressed\x12'\n" +
	"\x0ffallback_reason\x18\n" +
	" \x01(\tR\x0efallbackReason\"\xa8\x03\n" +
	"\x16SessionStartRulePacket\x12&\n" +
	"\x0frule_version_id\x18\x01 \x01(\x03R\rruleVersionId\x129\n" +
	"\x19legacy_behavioral_rule_id\x18\x02 \x01(\x03R\x16legacyBehavioralRuleId\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary\x12)\n" +
	"\x10evidence_handles\x18\b \x03(\tR\x0fevidenceHandles\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12!\n" +
	"\fbudget_class\x18\n" +
	" \x01(\tR\vbudgetClass\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority\x12-\n" +
	"\x12suppression_reason\x18\f \x01(\tR\x11suppressionReason\"\xbc\x02\n" +
	"\x12SessionStartMemory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12!\n" +
	"\fsource_agent\x18\x05 \x01(\tR\vsourceAgent\x12\x1b\n" +
	"\tedited_by\x18\x06 \x01(\tR\beditedBy\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\x18SessionStartMetaTagCount\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\xe3\x02\n" +
	"\x17SessionStartMetaSummary\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12>\n" +
	"\btop_tags\x18\x03 \x03(\v2#.engram.v1.SessionStartMetaTagCountR\atopTags\x12F\n" +
	"\x11oldest_created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0foldestCreatedAt\x12F\n" +
	"\x11newest_created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fnewestCreatedAt\x12=\n" +
	"\fgenerated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"@\n" +
	"\x17NegotiateVersionRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"\x8a\x01\n" +
	"\x18NegotiateVersionResponse\x12\x1e\n" +
	"\n" +
	"compatible\x18\x01 \x01(\bR\n" +
	"compatible\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12'\n" +
	"\x0fincompat_reason\x18\x03 \x01(\tR\x0eincompatReason\"\xd7\x01\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\fR\rargumentsJson\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12G\n" +
	"\x10project_identity\x18\x05 \x01(\v2\x1c.engram.v1.ProjectIdentityV2R\x0fprojectIdentity\"}\n" +
	"\x10CallToolResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\fR\vcontentJson\x12+\n" +
	"\x11canonical_project\x18\x03 \x01(\tR\x10canonicalProject\"\xbe\x01\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12G\n" +
	"\x10project_identity\x18\x04 \x01(\v2\x1c.engram.v1.ProjectIdentityV2R\x0fprojectIdentity\"\xba\x01\n" +
	"\x12InitializeResponse\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12/\n" +
	"\x05tools\x18\x03 \x03(\v2\x19.engram.v1.ToolDefinitionR\x05tools\x12+\n" +
	"\x11canonical_project\x18\x04 \x01(\tR\x10canonicalProject\"r\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\fR\x0finputSchemaJson\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xe3\x01\n" +
	"\rCodeChunkMeta\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1d\n" +
	"\n" +
	"byte_start\x18\x03 \x01(\x05R\tbyteStart\x12\x19\n" +
	"\bbyte_end\x18\x04 \x01(\x05R\abyteEnd\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"chunk_type\x18\x06 \x01(\tR\tchunkType\x12%\n" +
	"\x0econtent_sha256\x18\a \x01(\tR\rcontentSha256\"\x9a\x01\n" +
	"\x19CodeIndexNegotiateRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x10index_session_id\x18\x02 \x01(\tR\x0eindexSessionId\x124\n" +
	"\bmanifest\x18\x03 \x03(\v2\x18.engram.v1.CodeChunkMetaR\bmanifest\"`\n" +
	"\x1aCodeIndexNegotiateResponse\x12\x1f\n" +
	"\vneed_chunks\x18\x01 \x03(\tR\n" +
	"needChunks\x12!\n" +
	"\fstale_chunks\x18\x02 \x03(\tR\vstaleChunks\"\xa2\x01\n" +
	"\x0fCodeChunkUpload\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12(\n" +
	"\x10index_session_id\x18\x02 \x01(\tR\x0eindexSessionId\x12,\n" +
	"\x04meta\x18\x03 \x01(\v2\x18.engram.v1.CodeChunkMetaR\x04meta\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"f\n" +
	"\x16CodeIndexUploadReceipt\x12\x1a\n" +
	"\bembedded\x18\x01 \x01(\x05R\bembedded\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\xa2\x02\n" +
	"\x11ProjectIdentityV2\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12*\n" +
	"\x11legacy_project_id\x18\x02 \x01(\tR\x0flegacyProjectId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"git_remote\x18\x04 \x01(\tR\tgitRemote\x12#\n" +
	"\rrelative_path\x18\x05 \x01(\tR\frelativePath\x12$\n" +
	"\x0enon_git_anchor\x18\x06 \x01(\tR\fnonGitAnchor\x12(\n" +
	"\ranchor_shared\x18\a \x01(\bH\x00R\fanchorShared\x88\x01\x01B\x10\n" +
	"\x0e_anchor_shared*\x96\x01\n" +
	"\x10ProjectEventType\x12\"\n" +
	"\x1ePROJECT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_REMOVED\x10\x01\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_CREATED\x10\x02\x12\x1e\n" +
	"\x1aPROJECT_EVENT_TYPE_RENAMED\x10\x032\x85\x06\n" +
	"\rEngramService\x12C\n" +
	"\bCallTool\x12\x1a.engram.v1.CallToolRequest\x1a\x1b.engram.v1.CallToolResponse\x12I\n" +
	"\n" +
	"Initialize\x12\x1c.engram.v1.InitializeRequest\x1a\x1d.engram.v1.InitializeResponse\x127\n" +
	"\x04Ping\x12\x16.engram.v1.PingRequest\x1a\x17.engram.v1.PingResponse\x12[\n" +
	"\x10SyncProjectState\x12\".engram.v1.SyncProjectStateRequest\x1a#.engram.v1.SyncProjectStateResponse\x12K\n" +
	"\rProjectEvents\x12\x1f.engram.v1.ProjectEventsRequest\x1a\x17.engram.v1.ProjectEvent0\x01\x12m\n" +
	"\x16GetSessionStartContext\x12(.engram.v1.GetSessionStartContextRequest\x1a).engram.v1.GetSessionStartContextResponse\x12[\n" +
	"\x10NegotiateVersion\x12\".engram.v1.NegotiateVersionRequest\x1a#.engram.v1.NegotiateVersionResponse\x12a\n" +
	"\x12CodeIndexNegotiate\x12$.engram.v1.CodeIndexNegotiateRequest\x1a%.engram.v1.CodeIndexNegotiateResponse\x12R\n" +
	"\x0fCodeIndexUpload\x12\x1a.engram.v1.CodeChunkUpload\x1a!.engram.v1.CodeIndexUploadReceipt(\x01B3Z1github.com/thebtf/engram/proto/engram/v1;engramv1b\x06proto3"

var (
	file_proto_engram_v1_engram_proto_rawDescOnce sync.Once
	file_proto_engram_v1_engram_proto_rawDescData []byte
)

func file_proto_engram_v1_engram_proto_rawDescGZIP() []byte {
	file_proto_engram_v1_engram_proto_rawDescOnce.Do(func() {
		file_proto_engram_v1_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)))
	})
	return file_proto_engram_v1_engram_proto_rawDescData
}

var file_proto_engram_v1_engram_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_engram_v1_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_engram_v1_engram_proto_goTypes = []any{
	(ProjectEventType)(0),                  // 0: engram.v1.ProjectEventType
	(*SyncProjectStateRequest)(nil),        // 1: engram.v1.SyncProjectStateRequest
	(*SyncProjectStateResponse)(nil),       // 2: engram.v1.SyncProjectStateResponse
	(*ProjectEventsRequest)(nil),           // 3: engram.v1.ProjectEventsRequest
	(*ProjectEvent)(nil),                   // 4: engram.v1.ProjectEvent
	(*GetSessionStartContextRequest)(nil),  // 5: engram.v1.GetSessionStartContextRequest
	(*GetSessionStartContextResponse)(nil), // 6: engram.v1.GetSessionStartContextResponse
	(*SessionStartIssue)(nil),              // 7: engram.v1.SessionStartIssue
	(*SessionStartRule)(nil),               // 8: engram.v1.SessionStartRule
	(*SessionStartRuleRouter)(nil),         // 9: engram.v1.SessionStartRuleRouter
	(*SessionStartRulePacket)(nil),         // 10: engram.v1.SessionStartRulePacket
	(*SessionStartMemory)(nil),             // 11: engram.v1.SessionStartMemory
	(*SessionStartMetaTagCount)(nil),       // 12: engram.v1.SessionStartMetaTagCount
	(*SessionStartMetaSummary)(nil),        // 13: engram.v1.SessionStartMetaSummary
	(*NegotiateVersionRequest)(nil),        // 14: engram.v1.NegotiateVersionRequest
	(*NegotiateVersionResponse)(nil),       // 15: engram.v1.NegotiateVersionResponse
	(*CallToolRequest)(nil),                // 16: engram.v1.CallToolRequest
	(*CallToolResponse)(nil),               // 17: engram.v1.CallToolResponse
	(*InitializeRequest)(nil),              // 18: engram.v1.InitializeRequest
	(*InitializeResponse)(nil),             // 19: engram.v1.InitializeResponse
	(*ToolDefinition)(nil),                 // 20: engram.v1.ToolDefinition
	(*PingRequest)(nil),                    // 21: engram.v1.PingRequest
	(*PingResponse)(nil),                   // 22: engram.v1.PingResponse
	(*CodeChunkMeta)(nil),                  // 23: engram.v1.CodeChunkMeta
	(*CodeIndexNegotiateRequest)(nil),      // 24: engram.v1.CodeIndexNegotiateRequest
	(*CodeIndexNegotiateResponse)(nil),     // 25: engram.v1.CodeIndexNegotiateResponse
	(*CodeChunkUpload)(nil),                // 26: engram.v1.CodeChunkUpload
	(*CodeIndexUploadReceipt)(nil),         // 27: engram.v1.CodeIndexUploadReceipt
	(*ProjectIdentityV2)(nil),              // 28: engram.v1.ProjectIdentityV2
	nil,                                    // 29: engram.v1.ProjectEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil),          // 30: google.protobuf.Timestamp
}
var file_proto_engram_v1_engram_proto_depIdxs = []int32{
	0,  // 0: engram.v1.ProjectEvent.event_type:type_name -> engram.v1.ProjectEventType
	29, // 1: engram.v1.ProjectEvent.metadata:type_name -> engram.v1.ProjectEvent.MetadataEntry
	7,  // 2: engram.v1.GetSessionStartContextResponse.issues:type_name -> engram.v1.SessionStartIssue
	8,  // 3: engram.v1.GetSessionStartContextResponse.rules:type_name -> engram.v1.SessionStartRule
	11, // 4: engram.v1.GetSessionStartContextResponse.memories:type_name -> engram.v1.SessionStartMemory
	30, // 5: engram.v1.GetSessionStartContextResponse.generated_at:type_name -> google.protobuf.Timestamp
	9,  // 6: engram.v1.GetSessionStartContextResponse.rule_router:type_name -> engram.v1.SessionStartRuleRouter
	13, // 7: engram.v1.GetSessionStartContextResponse.meta_summary:type_name -> engram.v1.SessionStartMetaSummary
	30, // 8: engram.v1.SessionStartIssue.acknowledged_at:type_name -> google.protobuf.Timestamp
	30, // 9: engram.v1.SessionStartIssue.resolved_at:type_name -> google.protobuf.Timestamp
	30, // 10: engram.v1.SessionStartIssue.reopened_at:type_name -> google.protobuf.Timestamp
	30, // 11: engram.v1.SessionStartIssue.closed_at:type_name -> google.protobuf.Timestamp
	30, // 12: engram.v1.SessionStartIssue.created_at:type_name -> google.protobuf.Timestamp
	30, // 13: engram.v1.SessionStartIssue.updated_at:type_name -> google.protobuf.Timestamp
	30, // 14: engram.v1.SessionStartRule.created_at:type_name -> google.protobuf.Timestamp
	30, // 15: engram.v1.SessionStartRule.updated_at:type_name -> google.protobuf.Timestamp
	10, // 16: engram.v1.SessionStartRuleRouter.kernel:type_name -> engram.v1.SessionStartRulePacket
	10, // 17: engram.v1.SessionStartRuleRouter.contextual:type_name -> engram.v1.SessionStartRulePacket
	10, // 18: engram.v1.SessionStartRuleRouter.suppressed:type_name -> engram.v1.SessionStartRulePacket
	30, // 19: engram.v1.SessionStartMemory.created_at:type_name -> google.protobuf.Timestamp
	30, // 20: engram.v1.SessionStartMemory.updated_at:type_name -> google.protobuf.Timestamp
	12, // 21: engram.v1.SessionStartMetaSummary.top_tags:type_name -> engram.v1.SessionStartMetaTagCount
	30, // 22: engram.v1.SessionStartMetaSummary.oldest_created_at:type_name -> google.protobuf.Timestamp
	30, // 23: engram.v1.SessionStartMetaSummary.newest_created_at:type_name -> google.protobuf.Timestamp
	30, // 24: engram.v1.SessionStartMetaSummary.generated_at:type_name -> google.protobuf.Timestamp
	28, // 25: engram.v1.CallToolRequest.project_identity:type_name -> engram.v1.ProjectIdentityV2
	28, // 26: engram.v1.InitializeRequest.project_identity:type_name -> engram.v1.ProjectIdentityV2
	20, // 27: engram.v1.InitializeResponse.tools:type_name -> engram.v1.ToolDefinition
	23, // 28: engram.v1.CodeIndexNegotiateRequest.manifest:type_name -> engram.v1.CodeChunkMeta
	23, // 29: engram.v1.CodeChunkUpload.meta:type_name -> engram.v1.CodeChunkMeta
	16, // 30: engram.v1.EngramService.CallTool:input_type -> engram.v1.CallToolRequest
	18, // 31: engram.v1.EngramService.Initialize:input_type -> engram.v1.InitializeRequest
	21, // 32: engram.v1.EngramService.Ping:input_type -> engram.v1.PingRequest
	1,  // 33: engram.v1.EngramService.SyncProjectState:input_type -> engram.v1.SyncProjectStateRequest
	3,  // 34: engram.v1.EngramService.ProjectEvents:input_type -> engram.v1.ProjectEventsRequest
	5,  // 35: engram.v1.EngramService.GetSessionStartContext:input_type -> engram.v1.GetSessionStartContextRequest
	14, // 36: engram.v1.EngramService.NegotiateVersion:input_type -> engram.v1.NegotiateVersionRequest
	24, // 37: engram.v1.EngramService.CodeIndexNegotiate:input_type -> engram.v1.CodeIndexNegotiateRequest
	26, // 38: engram.v1.EngramService.CodeIndexUpload:input_type -> engram.v1.CodeChunkUpload
	17, // 39: engram.v1.EngramService.CallTool:output_type -> engram.v1.CallToolResponse
	19, // 40: engram.v1.EngramService.Initialize:output_type -> engram.v1.InitializeResponse
	22, // 41: engram.v1.EngramService.Ping:output_type -> engram.v1.PingResponse
	2,  // 42: engram.v1.EngramService.SyncProjectState:output_type -> engram.v1.SyncProjectStateResponse
	4,  // 43: engram.v1.EngramService.ProjectEvents:output_type -> engram.v1.ProjectEvent
	6,  // 44: engram.v1.EngramService.GetSessionStartContext:output_type -> engram.v1.GetSessionStartContextResponse
	15, // 45: engram.v1.EngramService.NegotiateVersion:output_type -> engram.v1.NegotiateVersionResponse
	25, // 46: engram.v1.EngramService.CodeIndexNegotiate:output_type -> engram.v1.CodeIndexNegotiateResponse
	27, // 47: engram.v1.EngramService.CodeIndexUpload:output_type -> engram.v1.CodeIndexUploadReceipt
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_proto_engram_v1_engram_proto_init() }
func file_proto_engram_v1_engram_proto_init() {
	if File_proto_engram_v1_engram_proto != nil {
		return
	}
	file_proto_engram_v1_engram_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engram_v1_engram_proto_goTypes,
		DependencyIndexes: file_proto_engram_v1_engram_proto_depIdxs,
		EnumInfos:         file_proto_engram_v1_engram_proto_enumTypes,
		MessageInfos:      file_proto_engram_v1_engram_proto_msgTypes,
	}.Build()
	File_proto_engram_v1_engram_proto = out.File
	file_proto_engram_v1_engram_proto_goTypes = nil
	file_proto_engram_v1_engram_proto_depIdxs = nil
}
