// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/engram/v1/engram.proto

package engramv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallToolRequest carries an MCP tool invocation.
type CallToolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MCP tool name (e.g., "store_memory", "recall", "search").
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Tool arguments as JSON bytes (same as MCP JSON-RPC params.arguments).
	ArgumentsJson []byte `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	// Project identity for scope isolation (from git-derived slug).
	Project string `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// Claude session ID for tracking and outcome propagation.
	SessionId     string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolRequest) Reset() {
	*x = CallToolRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolRequest) ProtoMessage() {}

func (x *CallToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolRequest.ProtoReflect.Descriptor instead.
func (*CallToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{0}
}

func (x *CallToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CallToolRequest) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *CallToolRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CallToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// CallToolResponse carries the result of an MCP tool call.
type CallToolResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the tool returned an error result.
	IsError bool `protobuf:"varint,1,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	// Tool result as JSON bytes (MCP content array serialized).
	ContentJson   []byte `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallToolResponse) Reset() {
	*x = CallToolResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallToolResponse) ProtoMessage() {}

func (x *CallToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallToolResponse.ProtoReflect.Descriptor instead.
func (*CallToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{1}
}

func (x *CallToolResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *CallToolResponse) GetContentJson() []byte {
	if x != nil {
		return x.ContentJson
	}
	return nil
}

// InitializeRequest is the handshake from daemon to server.
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *InitializeRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *InitializeRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// InitializeResponse carries server capabilities and tool definitions.
type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *InitializeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *InitializeResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// ToolDefinition describes a single MCP tool.
type ToolDefinition struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// JSON Schema for the tool's input parameters.
	InputSchemaJson []byte `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{5}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engram_v1_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_engram_v1_engram_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_engram_v1_engram_proto protoreflect.FileDescriptor

const file_proto_engram_v1_engram_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/engram/v1/engram.proto\x12\tengram.v1\"\x8e\x01\n" +
	"\x0fCallToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\fR\rargumentsJson\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"P\n" +
	"\x10CallToolResponse\x12\x19\n" +
	"\bis_error\x18\x01 \x01(\bR\aisError\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\fR\vcontentJson\"u\n" +
	"\x11InitializeRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\"\x8d\x01\n" +
	"\x12InitializeResponse\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12/\n" +
	"\x05tools\x18\x03 \x03(\v2\x19.engram.v1.ToolDefinitionR\x05tools\"r\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\fR\x0finputSchemaJson\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xd8\x01\n" +
	"\rEngramService\x12C\n" +
	"\bCallTool\x12\x1a.engram.v1.CallToolRequest\x1a\x1b.engram.v1.CallToolResponse\x12I\n" +
	"\n" +
	"Initialize\x12\x1c.engram.v1.InitializeRequest\x1a\x1d.engram.v1.InitializeResponse\x127\n" +
	"\x04Ping\x12\x16.engram.v1.PingRequest\x1a\x17.engram.v1.PingResponseB3Z1github.com/thebtf/engram/proto/engram/v1;engramv1b\x06proto3"

var (
	file_proto_engram_v1_engram_proto_rawDescOnce sync.Once
	file_proto_engram_v1_engram_proto_rawDescData []byte
)

func file_proto_engram_v1_engram_proto_rawDescGZIP() []byte {
	file_proto_engram_v1_engram_proto_rawDescOnce.Do(func() {
		file_proto_engram_v1_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)))
	})
	return file_proto_engram_v1_engram_proto_rawDescData
}

var file_proto_engram_v1_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_engram_v1_engram_proto_goTypes = []any{
	(*CallToolRequest)(nil),    // 0: engram.v1.CallToolRequest
	(*CallToolResponse)(nil),   // 1: engram.v1.CallToolResponse
	(*InitializeRequest)(nil),  // 2: engram.v1.InitializeRequest
	(*InitializeResponse)(nil), // 3: engram.v1.InitializeResponse
	(*ToolDefinition)(nil),     // 4: engram.v1.ToolDefinition
	(*PingRequest)(nil),        // 5: engram.v1.PingRequest
	(*PingResponse)(nil),       // 6: engram.v1.PingResponse
}
var file_proto_engram_v1_engram_proto_depIdxs = []int32{
	4, // 0: engram.v1.InitializeResponse.tools:type_name -> engram.v1.ToolDefinition
	0, // 1: engram.v1.EngramService.CallTool:input_type -> engram.v1.CallToolRequest
	2, // 2: engram.v1.EngramService.Initialize:input_type -> engram.v1.InitializeRequest
	5, // 3: engram.v1.EngramService.Ping:input_type -> engram.v1.PingRequest
	1, // 4: engram.v1.EngramService.CallTool:output_type -> engram.v1.CallToolResponse
	3, // 5: engram.v1.EngramService.Initialize:output_type -> engram.v1.InitializeResponse
	6, // 6: engram.v1.EngramService.Ping:output_type -> engram.v1.PingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_engram_v1_engram_proto_init() }
func file_proto_engram_v1_engram_proto_init() {
	if File_proto_engram_v1_engram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engram_v1_engram_proto_rawDesc), len(file_proto_engram_v1_engram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engram_v1_engram_proto_goTypes,
		DependencyIndexes: file_proto_engram_v1_engram_proto_depIdxs,
		MessageInfos:      file_proto_engram_v1_engram_proto_msgTypes,
	}.Build()
	File_proto_engram_v1_engram_proto = out.File
	file_proto_engram_v1_engram_proto_goTypes = nil
	file_proto_engram_v1_engram_proto_depIdxs = nil
}
