// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/engram/v1/engram.proto

package engramv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngramService_CallTool_FullMethodName         = "/engram.v1.EngramService/CallTool"
	EngramService_Initialize_FullMethodName       = "/engram.v1.EngramService/Initialize"
	EngramService_Ping_FullMethodName             = "/engram.v1.EngramService/Ping"
	EngramService_SyncProjectState_FullMethodName = "/engram.v1.EngramService/SyncProjectState"
	EngramService_ProjectEvents_FullMethodName    = "/engram.v1.EngramService/ProjectEvents"
)

// EngramServiceClient is the client API for EngramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngramService provides MCP tool access via gRPC.
// The daemon connects to this service and translates MCP JSON-RPC to gRPC calls.
type EngramServiceClient interface {
	// CallTool dispatches a single MCP tool call.
	// Generic: tool_name + JSON args, matching the MCP tools/call pattern.
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
	// Initialize returns server info and the list of available tools.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// Ping is a lightweight health check.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// SyncProjectState reconciles the daemon's local project registry
	// against the server's authoritative list. Called by the daemon every
	// 60 s as a heartbeat. The response drives ProjectRemovalAware fan-out
	// for any project the daemon tracks locally but the server no longer
	// knows about. Idempotent — multiple daemons can call concurrently.
	SyncProjectState(ctx context.Context, in *SyncProjectStateRequest, opts ...grpc.CallOption) (*SyncProjectStateResponse, error)
	// ProjectEvents pushes project-lifecycle events in real time. Server-
	// streaming RPC; the stream stays open for the daemon's lifetime.
	// Delivery is at-least-once; the daemon is responsible for dedup.
	ProjectEvents(ctx context.Context, in *ProjectEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectEvent], error)
}

type engramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngramServiceClient(cc grpc.ClientConnInterface) EngramServiceClient {
	return &engramServiceClient{cc}
}

func (c *engramServiceClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, EngramService_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, EngramService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EngramService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) SyncProjectState(ctx context.Context, in *SyncProjectStateRequest, opts ...grpc.CallOption) (*SyncProjectStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProjectStateResponse)
	err := c.cc.Invoke(ctx, EngramService_SyncProjectState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) ProjectEvents(ctx context.Context, in *ProjectEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngramService_ServiceDesc.Streams[0], EngramService_ProjectEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectEventsRequest, ProjectEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_ProjectEventsClient = grpc.ServerStreamingClient[ProjectEvent]

// EngramServiceServer is the server API for EngramService service.
// All implementations must embed UnimplementedEngramServiceServer
// for forward compatibility.
//
// EngramService provides MCP tool access via gRPC.
// The daemon connects to this service and translates MCP JSON-RPC to gRPC calls.
type EngramServiceServer interface {
	// CallTool dispatches a single MCP tool call.
	// Generic: tool_name + JSON args, matching the MCP tools/call pattern.
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	// Initialize returns server info and the list of available tools.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// Ping is a lightweight health check.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// SyncProjectState reconciles the daemon's local project registry
	// against the server's authoritative list. Called by the daemon every
	// 60 s as a heartbeat. The response drives ProjectRemovalAware fan-out
	// for any project the daemon tracks locally but the server no longer
	// knows about. Idempotent — multiple daemons can call concurrently.
	SyncProjectState(context.Context, *SyncProjectStateRequest) (*SyncProjectStateResponse, error)
	// ProjectEvents pushes project-lifecycle events in real time. Server-
	// streaming RPC; the stream stays open for the daemon's lifetime.
	// Delivery is at-least-once; the daemon is responsible for dedup.
	ProjectEvents(*ProjectEventsRequest, grpc.ServerStreamingServer[ProjectEvent]) error
	mustEmbedUnimplementedEngramServiceServer()
}

// UnimplementedEngramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngramServiceServer struct{}

func (UnimplementedEngramServiceServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedEngramServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedEngramServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEngramServiceServer) SyncProjectState(context.Context, *SyncProjectStateRequest) (*SyncProjectStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncProjectState not implemented")
}
func (UnimplementedEngramServiceServer) ProjectEvents(*ProjectEventsRequest, grpc.ServerStreamingServer[ProjectEvent]) error {
	return status.Error(codes.Unimplemented, "method ProjectEvents not implemented")
}
func (UnimplementedEngramServiceServer) mustEmbedUnimplementedEngramServiceServer() {}
func (UnimplementedEngramServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngramServiceServer will
// result in compilation errors.
type UnsafeEngramServiceServer interface {
	mustEmbedUnimplementedEngramServiceServer()
}

func RegisterEngramServiceServer(s grpc.ServiceRegistrar, srv EngramServiceServer) {
	// If the following call panics, it indicates UnimplementedEngramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngramService_ServiceDesc, srv)
}

func _EngramService_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_SyncProjectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProjectStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).SyncProjectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_SyncProjectState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).SyncProjectState(ctx, req.(*SyncProjectStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_ProjectEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngramServiceServer).ProjectEvents(m, &grpc.GenericServerStream[ProjectEventsRequest, ProjectEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_ProjectEventsServer = grpc.ServerStreamingServer[ProjectEvent]

// EngramService_ServiceDesc is the grpc.ServiceDesc for EngramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engram.v1.EngramService",
	HandlerType: (*EngramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTool",
			Handler:    _EngramService_CallTool_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _EngramService_Initialize_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _EngramService_Ping_Handler,
		},
		{
			MethodName: "SyncProjectState",
			Handler:    _EngramService_SyncProjectState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProjectEvents",
			Handler:       _EngramService_ProjectEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/engram/v1/engram.proto",
}
