// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/engram/v1/engram.proto

package engramv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngramService_CallTool_FullMethodName                  = "/engram.v1.EngramService/CallTool"
	EngramService_Initialize_FullMethodName                = "/engram.v1.EngramService/Initialize"
	EngramService_Ping_FullMethodName                      = "/engram.v1.EngramService/Ping"
	EngramService_SyncProjectState_FullMethodName          = "/engram.v1.EngramService/SyncProjectState"
	EngramService_ProjectEvents_FullMethodName             = "/engram.v1.EngramService/ProjectEvents"
	EngramService_GetSessionStartContext_FullMethodName    = "/engram.v1.EngramService/GetSessionStartContext"
	EngramService_GetAmbientCandidates_FullMethodName      = "/engram.v1.EngramService/GetAmbientCandidates"
	EngramService_NegotiateVersion_FullMethodName          = "/engram.v1.EngramService/NegotiateVersion"
	EngramService_CodeIndexNegotiate_FullMethodName        = "/engram.v1.EngramService/CodeIndexNegotiate"
	EngramService_CodeIndexUpload_FullMethodName           = "/engram.v1.EngramService/CodeIndexUpload"
	EngramService_RegisterProjectIdentityV3_FullMethodName = "/engram.v1.EngramService/RegisterProjectIdentityV3"
	EngramService_Bind_FullMethodName                      = "/engram.v1.EngramService/Bind"
	EngramService_Advise_FullMethodName                    = "/engram.v1.EngramService/Advise"
	EngramService_Observe_FullMethodName                   = "/engram.v1.EngramService/Observe"
	EngramService_BindCodeContext_FullMethodName           = "/engram.v1.EngramService/BindCodeContext"
	EngramService_BeginCodeIndex_FullMethodName            = "/engram.v1.EngramService/BeginCodeIndex"
	EngramService_StageCodeIndex_FullMethodName            = "/engram.v1.EngramService/StageCodeIndex"
	EngramService_FinalizeCodeIndex_FullMethodName         = "/engram.v1.EngramService/FinalizeCodeIndex"
	EngramService_QueryCode_FullMethodName                 = "/engram.v1.EngramService/QueryCode"
	EngramService_ExploreCode_FullMethodName               = "/engram.v1.EngramService/ExploreCode"
)

// EngramServiceClient is the client API for EngramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngramService provides MCP tool access via gRPC.
// The daemon connects to this service and translates MCP JSON-RPC to gRPC calls.
type EngramServiceClient interface {
	// CallTool dispatches a single MCP tool call.
	// Generic: tool_name + JSON args, matching the MCP tools/call pattern.
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
	// Initialize returns server info and the list of available tools.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// Ping is a lightweight health check.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// SyncProjectState reconciles the daemon's local project registry
	// against the server's authoritative list. Called by the daemon every
	// 60 s as a heartbeat. The response drives ProjectRemovalAware fan-out
	// for any project the daemon tracks locally but the server no longer
	// knows about. Idempotent — multiple daemons can call concurrently.
	SyncProjectState(ctx context.Context, in *SyncProjectStateRequest, opts ...grpc.CallOption) (*SyncProjectStateResponse, error)
	// ProjectEvents pushes project-lifecycle events in real time. Server-
	// streaming RPC; the stream stays open for the daemon's lifetime.
	// Delivery is at-least-once; the daemon is responsible for dedup.
	ProjectEvents(ctx context.Context, in *ProjectEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectEvent], error)
	// GetSessionStartContext returns static session-start context entities for a project.
	// No ranking or LLM filtering is applied; the server returns SQL-backed entities only.
	GetSessionStartContext(ctx context.Context, in *GetSessionStartContextRequest, opts ...grpc.CallOption) (*GetSessionStartContextResponse, error)
	// GetAmbientCandidates returns bounded same-turn ambient context through the
	// existing service. It is private to the credential-neutral legacy bridge.
	GetAmbientCandidates(ctx context.Context, in *GetAmbientCandidatesRequest, opts ...grpc.CallOption) (*GetAmbientCandidatesResponse, error)
	// NegotiateVersion validates MAJOR-version compatibility between client and server.
	NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error)
	// CodeIndexNegotiate performs a delta negotiation: the client sends its full
	// manifest of chunk metadata; the server returns which chunks it needs
	// (client must upload) and which existing server-side chunks are now stale
	// (client has dropped them). Stale rows are swept automatically at the end
	// of the subsequent CodeIndexUpload stream.
	CodeIndexNegotiate(ctx context.Context, in *CodeIndexNegotiateRequest, opts ...grpc.CallOption) (*CodeIndexNegotiateResponse, error)
	// CodeIndexUpload is a client-streaming RPC. The client streams the chunk
	// payloads identified as needed by CodeIndexNegotiate, then closes the
	// stream. On close the server deletes stale chunks (those whose
	// index_session_id does not match the negotiated session) and returns a
	// receipt with counts of embedded and deleted rows.
	CodeIndexUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CodeChunkUpload, CodeIndexUploadReceipt], error)
	// RegisterProjectIdentityV3 explicitly establishes a V3 anchor binding.
	// Authentication and registration authority are derived solely by the server.
	RegisterProjectIdentityV3(ctx context.Context, in *RegisterProjectIdentityV3Request, opts ...grpc.CallOption) (*RegisterProjectIdentityV3Response, error)
	// Bind establishes a private host-advisor capability binding.
	Bind(ctx context.Context, in *HostAdvisorBindRequest, opts ...grpc.CallOption) (*HostAdvisorBindResponse, error)
	// Advise is reserved for the host-advisor delivery semantics owned by HAP-03.
	Advise(ctx context.Context, in *HostAdvisorAdviseRequest, opts ...grpc.CallOption) (*HostAdvisorAdviseResponse, error)
	// Observe is reserved for host-advisor observation semantics owned by HAP-03.
	Observe(ctx context.Context, in *HostAdvisorObserveRequest, opts ...grpc.CallOption) (*HostAdvisorObserveResponse, error)
	// BindCodeContext resolves a scoped immutable code context for one client session.
	BindCodeContext(ctx context.Context, in *BindCodeContextRequest, opts ...grpc.CallOption) (*BindCodeContextResponse, error)
	// BeginCodeIndex starts a fenced, checkout-scoped index build.
	BeginCodeIndex(ctx context.Context, in *BeginCodeIndexRequest, opts ...grpc.CallOption) (*BeginCodeIndexResponse, error)
	// StageCodeIndex receives ordered parts for one fenced index build.
	StageCodeIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StageCodeIndexFrame, StageCodeIndexResponse], error)
	// FinalizeCodeIndex explicitly publishes a completed staged manifest.
	FinalizeCodeIndex(ctx context.Context, in *FinalizeCodeIndexRequest, opts ...grpc.CallOption) (*FinalizeCodeIndexResponse, error)
	// QueryCode returns a bounded result payload for one pinned context.
	QueryCode(ctx context.Context, in *QueryCodeRequest, opts ...grpc.CallOption) (*QueryCodeResponse, error)
	// ExploreCode returns a bounded graph payload for one pinned context.
	ExploreCode(ctx context.Context, in *ExploreCodeRequest, opts ...grpc.CallOption) (*ExploreCodeResponse, error)
}

type engramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngramServiceClient(cc grpc.ClientConnInterface) EngramServiceClient {
	return &engramServiceClient{cc}
}

func (c *engramServiceClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, EngramService_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, EngramService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EngramService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) SyncProjectState(ctx context.Context, in *SyncProjectStateRequest, opts ...grpc.CallOption) (*SyncProjectStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncProjectStateResponse)
	err := c.cc.Invoke(ctx, EngramService_SyncProjectState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) ProjectEvents(ctx context.Context, in *ProjectEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProjectEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngramService_ServiceDesc.Streams[0], EngramService_ProjectEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectEventsRequest, ProjectEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_ProjectEventsClient = grpc.ServerStreamingClient[ProjectEvent]

func (c *engramServiceClient) GetSessionStartContext(ctx context.Context, in *GetSessionStartContextRequest, opts ...grpc.CallOption) (*GetSessionStartContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStartContextResponse)
	err := c.cc.Invoke(ctx, EngramService_GetSessionStartContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) GetAmbientCandidates(ctx context.Context, in *GetAmbientCandidatesRequest, opts ...grpc.CallOption) (*GetAmbientCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAmbientCandidatesResponse)
	err := c.cc.Invoke(ctx, EngramService_GetAmbientCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) NegotiateVersion(ctx context.Context, in *NegotiateVersionRequest, opts ...grpc.CallOption) (*NegotiateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegotiateVersionResponse)
	err := c.cc.Invoke(ctx, EngramService_NegotiateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) CodeIndexNegotiate(ctx context.Context, in *CodeIndexNegotiateRequest, opts ...grpc.CallOption) (*CodeIndexNegotiateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodeIndexNegotiateResponse)
	err := c.cc.Invoke(ctx, EngramService_CodeIndexNegotiate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) CodeIndexUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CodeChunkUpload, CodeIndexUploadReceipt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngramService_ServiceDesc.Streams[1], EngramService_CodeIndexUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CodeChunkUpload, CodeIndexUploadReceipt]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_CodeIndexUploadClient = grpc.ClientStreamingClient[CodeChunkUpload, CodeIndexUploadReceipt]

func (c *engramServiceClient) RegisterProjectIdentityV3(ctx context.Context, in *RegisterProjectIdentityV3Request, opts ...grpc.CallOption) (*RegisterProjectIdentityV3Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterProjectIdentityV3Response)
	err := c.cc.Invoke(ctx, EngramService_RegisterProjectIdentityV3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Bind(ctx context.Context, in *HostAdvisorBindRequest, opts ...grpc.CallOption) (*HostAdvisorBindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAdvisorBindResponse)
	err := c.cc.Invoke(ctx, EngramService_Bind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Advise(ctx context.Context, in *HostAdvisorAdviseRequest, opts ...grpc.CallOption) (*HostAdvisorAdviseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAdvisorAdviseResponse)
	err := c.cc.Invoke(ctx, EngramService_Advise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) Observe(ctx context.Context, in *HostAdvisorObserveRequest, opts ...grpc.CallOption) (*HostAdvisorObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostAdvisorObserveResponse)
	err := c.cc.Invoke(ctx, EngramService_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) BindCodeContext(ctx context.Context, in *BindCodeContextRequest, opts ...grpc.CallOption) (*BindCodeContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindCodeContextResponse)
	err := c.cc.Invoke(ctx, EngramService_BindCodeContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) BeginCodeIndex(ctx context.Context, in *BeginCodeIndexRequest, opts ...grpc.CallOption) (*BeginCodeIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginCodeIndexResponse)
	err := c.cc.Invoke(ctx, EngramService_BeginCodeIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) StageCodeIndex(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StageCodeIndexFrame, StageCodeIndexResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EngramService_ServiceDesc.Streams[2], EngramService_StageCodeIndex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StageCodeIndexFrame, StageCodeIndexResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_StageCodeIndexClient = grpc.ClientStreamingClient[StageCodeIndexFrame, StageCodeIndexResponse]

func (c *engramServiceClient) FinalizeCodeIndex(ctx context.Context, in *FinalizeCodeIndexRequest, opts ...grpc.CallOption) (*FinalizeCodeIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeCodeIndexResponse)
	err := c.cc.Invoke(ctx, EngramService_FinalizeCodeIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) QueryCode(ctx context.Context, in *QueryCodeRequest, opts ...grpc.CallOption) (*QueryCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryCodeResponse)
	err := c.cc.Invoke(ctx, EngramService_QueryCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramServiceClient) ExploreCode(ctx context.Context, in *ExploreCodeRequest, opts ...grpc.CallOption) (*ExploreCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExploreCodeResponse)
	err := c.cc.Invoke(ctx, EngramService_ExploreCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngramServiceServer is the server API for EngramService service.
// All implementations must embed UnimplementedEngramServiceServer
// for forward compatibility.
//
// EngramService provides MCP tool access via gRPC.
// The daemon connects to this service and translates MCP JSON-RPC to gRPC calls.
type EngramServiceServer interface {
	// CallTool dispatches a single MCP tool call.
	// Generic: tool_name + JSON args, matching the MCP tools/call pattern.
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	// Initialize returns server info and the list of available tools.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// Ping is a lightweight health check.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// SyncProjectState reconciles the daemon's local project registry
	// against the server's authoritative list. Called by the daemon every
	// 60 s as a heartbeat. The response drives ProjectRemovalAware fan-out
	// for any project the daemon tracks locally but the server no longer
	// knows about. Idempotent — multiple daemons can call concurrently.
	SyncProjectState(context.Context, *SyncProjectStateRequest) (*SyncProjectStateResponse, error)
	// ProjectEvents pushes project-lifecycle events in real time. Server-
	// streaming RPC; the stream stays open for the daemon's lifetime.
	// Delivery is at-least-once; the daemon is responsible for dedup.
	ProjectEvents(*ProjectEventsRequest, grpc.ServerStreamingServer[ProjectEvent]) error
	// GetSessionStartContext returns static session-start context entities for a project.
	// No ranking or LLM filtering is applied; the server returns SQL-backed entities only.
	GetSessionStartContext(context.Context, *GetSessionStartContextRequest) (*GetSessionStartContextResponse, error)
	// GetAmbientCandidates returns bounded same-turn ambient context through the
	// existing service. It is private to the credential-neutral legacy bridge.
	GetAmbientCandidates(context.Context, *GetAmbientCandidatesRequest) (*GetAmbientCandidatesResponse, error)
	// NegotiateVersion validates MAJOR-version compatibility between client and server.
	NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error)
	// CodeIndexNegotiate performs a delta negotiation: the client sends its full
	// manifest of chunk metadata; the server returns which chunks it needs
	// (client must upload) and which existing server-side chunks are now stale
	// (client has dropped them). Stale rows are swept automatically at the end
	// of the subsequent CodeIndexUpload stream.
	CodeIndexNegotiate(context.Context, *CodeIndexNegotiateRequest) (*CodeIndexNegotiateResponse, error)
	// CodeIndexUpload is a client-streaming RPC. The client streams the chunk
	// payloads identified as needed by CodeIndexNegotiate, then closes the
	// stream. On close the server deletes stale chunks (those whose
	// index_session_id does not match the negotiated session) and returns a
	// receipt with counts of embedded and deleted rows.
	CodeIndexUpload(grpc.ClientStreamingServer[CodeChunkUpload, CodeIndexUploadReceipt]) error
	// RegisterProjectIdentityV3 explicitly establishes a V3 anchor binding.
	// Authentication and registration authority are derived solely by the server.
	RegisterProjectIdentityV3(context.Context, *RegisterProjectIdentityV3Request) (*RegisterProjectIdentityV3Response, error)
	// Bind establishes a private host-advisor capability binding.
	Bind(context.Context, *HostAdvisorBindRequest) (*HostAdvisorBindResponse, error)
	// Advise is reserved for the host-advisor delivery semantics owned by HAP-03.
	Advise(context.Context, *HostAdvisorAdviseRequest) (*HostAdvisorAdviseResponse, error)
	// Observe is reserved for host-advisor observation semantics owned by HAP-03.
	Observe(context.Context, *HostAdvisorObserveRequest) (*HostAdvisorObserveResponse, error)
	// BindCodeContext resolves a scoped immutable code context for one client session.
	BindCodeContext(context.Context, *BindCodeContextRequest) (*BindCodeContextResponse, error)
	// BeginCodeIndex starts a fenced, checkout-scoped index build.
	BeginCodeIndex(context.Context, *BeginCodeIndexRequest) (*BeginCodeIndexResponse, error)
	// StageCodeIndex receives ordered parts for one fenced index build.
	StageCodeIndex(grpc.ClientStreamingServer[StageCodeIndexFrame, StageCodeIndexResponse]) error
	// FinalizeCodeIndex explicitly publishes a completed staged manifest.
	FinalizeCodeIndex(context.Context, *FinalizeCodeIndexRequest) (*FinalizeCodeIndexResponse, error)
	// QueryCode returns a bounded result payload for one pinned context.
	QueryCode(context.Context, *QueryCodeRequest) (*QueryCodeResponse, error)
	// ExploreCode returns a bounded graph payload for one pinned context.
	ExploreCode(context.Context, *ExploreCodeRequest) (*ExploreCodeResponse, error)
	mustEmbedUnimplementedEngramServiceServer()
}

// UnimplementedEngramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngramServiceServer struct{}

func (UnimplementedEngramServiceServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedEngramServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedEngramServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEngramServiceServer) SyncProjectState(context.Context, *SyncProjectStateRequest) (*SyncProjectStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncProjectState not implemented")
}
func (UnimplementedEngramServiceServer) ProjectEvents(*ProjectEventsRequest, grpc.ServerStreamingServer[ProjectEvent]) error {
	return status.Error(codes.Unimplemented, "method ProjectEvents not implemented")
}
func (UnimplementedEngramServiceServer) GetSessionStartContext(context.Context, *GetSessionStartContextRequest) (*GetSessionStartContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionStartContext not implemented")
}
func (UnimplementedEngramServiceServer) GetAmbientCandidates(context.Context, *GetAmbientCandidatesRequest) (*GetAmbientCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAmbientCandidates not implemented")
}
func (UnimplementedEngramServiceServer) NegotiateVersion(context.Context, *NegotiateVersionRequest) (*NegotiateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NegotiateVersion not implemented")
}
func (UnimplementedEngramServiceServer) CodeIndexNegotiate(context.Context, *CodeIndexNegotiateRequest) (*CodeIndexNegotiateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CodeIndexNegotiate not implemented")
}
func (UnimplementedEngramServiceServer) CodeIndexUpload(grpc.ClientStreamingServer[CodeChunkUpload, CodeIndexUploadReceipt]) error {
	return status.Error(codes.Unimplemented, "method CodeIndexUpload not implemented")
}
func (UnimplementedEngramServiceServer) RegisterProjectIdentityV3(context.Context, *RegisterProjectIdentityV3Request) (*RegisterProjectIdentityV3Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterProjectIdentityV3 not implemented")
}
func (UnimplementedEngramServiceServer) Bind(context.Context, *HostAdvisorBindRequest) (*HostAdvisorBindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedEngramServiceServer) Advise(context.Context, *HostAdvisorAdviseRequest) (*HostAdvisorAdviseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Advise not implemented")
}
func (UnimplementedEngramServiceServer) Observe(context.Context, *HostAdvisorObserveRequest) (*HostAdvisorObserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedEngramServiceServer) BindCodeContext(context.Context, *BindCodeContextRequest) (*BindCodeContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindCodeContext not implemented")
}
func (UnimplementedEngramServiceServer) BeginCodeIndex(context.Context, *BeginCodeIndexRequest) (*BeginCodeIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginCodeIndex not implemented")
}
func (UnimplementedEngramServiceServer) StageCodeIndex(grpc.ClientStreamingServer[StageCodeIndexFrame, StageCodeIndexResponse]) error {
	return status.Error(codes.Unimplemented, "method StageCodeIndex not implemented")
}
func (UnimplementedEngramServiceServer) FinalizeCodeIndex(context.Context, *FinalizeCodeIndexRequest) (*FinalizeCodeIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeCodeIndex not implemented")
}
func (UnimplementedEngramServiceServer) QueryCode(context.Context, *QueryCodeRequest) (*QueryCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryCode not implemented")
}
func (UnimplementedEngramServiceServer) ExploreCode(context.Context, *ExploreCodeRequest) (*ExploreCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExploreCode not implemented")
}
func (UnimplementedEngramServiceServer) mustEmbedUnimplementedEngramServiceServer() {}
func (UnimplementedEngramServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngramServiceServer will
// result in compilation errors.
type UnsafeEngramServiceServer interface {
	mustEmbedUnimplementedEngramServiceServer()
}

func RegisterEngramServiceServer(s grpc.ServiceRegistrar, srv EngramServiceServer) {
	// If the following call panics, it indicates UnimplementedEngramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngramService_ServiceDesc, srv)
}

func _EngramService_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_SyncProjectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncProjectStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).SyncProjectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_SyncProjectState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).SyncProjectState(ctx, req.(*SyncProjectStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_ProjectEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProjectEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngramServiceServer).ProjectEvents(m, &grpc.GenericServerStream[ProjectEventsRequest, ProjectEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_ProjectEventsServer = grpc.ServerStreamingServer[ProjectEvent]

func _EngramService_GetSessionStartContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStartContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).GetSessionStartContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_GetSessionStartContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).GetSessionStartContext(ctx, req.(*GetSessionStartContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_GetAmbientCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAmbientCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).GetAmbientCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_GetAmbientCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).GetAmbientCandidates(ctx, req.(*GetAmbientCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_NegotiateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegotiateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).NegotiateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_NegotiateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).NegotiateVersion(ctx, req.(*NegotiateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_CodeIndexNegotiate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeIndexNegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).CodeIndexNegotiate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_CodeIndexNegotiate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).CodeIndexNegotiate(ctx, req.(*CodeIndexNegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_CodeIndexUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EngramServiceServer).CodeIndexUpload(&grpc.GenericServerStream[CodeChunkUpload, CodeIndexUploadReceipt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_CodeIndexUploadServer = grpc.ClientStreamingServer[CodeChunkUpload, CodeIndexUploadReceipt]

func _EngramService_RegisterProjectIdentityV3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectIdentityV3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).RegisterProjectIdentityV3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_RegisterProjectIdentityV3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).RegisterProjectIdentityV3(ctx, req.(*RegisterProjectIdentityV3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Bind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostAdvisorBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Bind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Bind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Bind(ctx, req.(*HostAdvisorBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Advise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostAdvisorAdviseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Advise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Advise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Advise(ctx, req.(*HostAdvisorAdviseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostAdvisorObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).Observe(ctx, req.(*HostAdvisorObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_BindCodeContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindCodeContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).BindCodeContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_BindCodeContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).BindCodeContext(ctx, req.(*BindCodeContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_BeginCodeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginCodeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).BeginCodeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_BeginCodeIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).BeginCodeIndex(ctx, req.(*BeginCodeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_StageCodeIndex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EngramServiceServer).StageCodeIndex(&grpc.GenericServerStream[StageCodeIndexFrame, StageCodeIndexResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EngramService_StageCodeIndexServer = grpc.ClientStreamingServer[StageCodeIndexFrame, StageCodeIndexResponse]

func _EngramService_FinalizeCodeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeCodeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).FinalizeCodeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_FinalizeCodeIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).FinalizeCodeIndex(ctx, req.(*FinalizeCodeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_QueryCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).QueryCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_QueryCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).QueryCode(ctx, req.(*QueryCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngramService_ExploreCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploreCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServiceServer).ExploreCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngramService_ExploreCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServiceServer).ExploreCode(ctx, req.(*ExploreCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngramService_ServiceDesc is the grpc.ServiceDesc for EngramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engram.v1.EngramService",
	HandlerType: (*EngramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallTool",
			Handler:    _EngramService_CallTool_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _EngramService_Initialize_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _EngramService_Ping_Handler,
		},
		{
			MethodName: "SyncProjectState",
			Handler:    _EngramService_SyncProjectState_Handler,
		},
		{
			MethodName: "GetSessionStartContext",
			Handler:    _EngramService_GetSessionStartContext_Handler,
		},
		{
			MethodName: "GetAmbientCandidates",
			Handler:    _EngramService_GetAmbientCandidates_Handler,
		},
		{
			MethodName: "NegotiateVersion",
			Handler:    _EngramService_NegotiateVersion_Handler,
		},
		{
			MethodName: "CodeIndexNegotiate",
			Handler:    _EngramService_CodeIndexNegotiate_Handler,
		},
		{
			MethodName: "RegisterProjectIdentityV3",
			Handler:    _EngramService_RegisterProjectIdentityV3_Handler,
		},
		{
			MethodName: "Bind",
			Handler:    _EngramService_Bind_Handler,
		},
		{
			MethodName: "Advise",
			Handler:    _EngramService_Advise_Handler,
		},
		{
			MethodName: "Observe",
			Handler:    _EngramService_Observe_Handler,
		},
		{
			MethodName: "BindCodeContext",
			Handler:    _EngramService_BindCodeContext_Handler,
		},
		{
			MethodName: "BeginCodeIndex",
			Handler:    _EngramService_BeginCodeIndex_Handler,
		},
		{
			MethodName: "FinalizeCodeIndex",
			Handler:    _EngramService_FinalizeCodeIndex_Handler,
		},
		{
			MethodName: "QueryCode",
			Handler:    _EngramService_QueryCode_Handler,
		},
		{
			MethodName: "ExploreCode",
			Handler:    _EngramService_ExploreCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProjectEvents",
			Handler:       _EngramService_ProjectEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CodeIndexUpload",
			Handler:       _EngramService_CodeIndexUpload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StageCodeIndex",
			Handler:       _EngramService_StageCodeIndex_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/engram/v1/engram.proto",
}
