package gorm

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// BrowserTabBindingLeaseState is the lifecycle state of the current document lease.
type BrowserTabBindingLeaseState string

const (
	BrowserTabBindingLeaseLive    BrowserTabBindingLeaseState = "live"
	BrowserTabBindingLeaseClosed  BrowserTabBindingLeaseState = "closed"
	BrowserTabBindingLeaseExpired BrowserTabBindingLeaseState = "expired"
)

// BrowserTabBindingResumeState describes whether a resume replaced the document or
// must wait for the previous document lease to finish.
type BrowserTabBindingResumeState string

const (
	BrowserTabBindingResumed       BrowserTabBindingResumeState = "resumed"
	BrowserTabBindingReloadPending BrowserTabBindingResumeState = "reload_pending"
)

var (
	// ErrBrowserTabBindingDenied deliberately makes every absent, foreign, stale,
	// expired, or replayed binding/proof/material indistinguishable to callers.
	ErrBrowserTabBindingDenied             = errors.New("browser tab binding denied")
	errBrowserTabBindingStoreNotConfigured = errors.New("browser tab binding store is not configured")
)

// BrowserTabBinding persists server-owned binding state. It intentionally has no
// raw document proof, document nonce, resume nonce, or reload token fields: the
// application persists only fixed-width digests of those browser-held values.
type BrowserTabBinding struct {
	TabBindingID            string                      `gorm:"column:tab_binding_id;type:uuid;primaryKey" json:"tab_binding_id"`
	SubjectUserID           int64                       `gorm:"column:subject_user_id;not null" json:"subject_user_id"`
	SessionID               string                      `gorm:"column:session_id;type:text;not null" json:"-"`
	ResumeNonceDigest       []byte                      `gorm:"column:resume_nonce_digest;type:bytea;not null" json:"-"`
	DocumentProofDigest     []byte                      `gorm:"column:document_proof_digest;type:bytea;not null" json:"-"`
	ReloadTokenDigest       []byte                      `gorm:"column:reload_token_digest;type:bytea;not null" json:"-"`
	DocumentLeaseState      BrowserTabBindingLeaseState `gorm:"column:document_lease_state;type:text;not null" json:"document_lease_state"`
	DocumentLeaseExpiresAt  time.Time                   `gorm:"column:document_lease_expires_at;type:timestamptz;not null" json:"document_lease_expires_at"`
	PinnedSourceID          *string                     `gorm:"column:pinned_source_id;type:uuid" json:"-"`
	PinnedCheckoutID        *string                     `gorm:"column:pinned_checkout_id;type:uuid" json:"-"`
	PinnedViewID            *string                     `gorm:"column:pinned_view_id;type:uuid" json:"-"`
	PinnedAnalysisProfileID *string                     `gorm:"column:pinned_analysis_profile_id;type:uuid" json:"-"`
	PinnedGeneration        *int64                      `gorm:"column:pinned_generation" json:"-"`
	BindingExpiresAt        time.Time                   `gorm:"column:binding_expires_at;type:timestamptz;not null" json:"binding_expires_at"`
	CreatedAt               time.Time                   `gorm:"column:created_at;type:timestamptz;not null" json:"created_at"`
	UpdatedAt               time.Time                   `gorm:"column:updated_at;type:timestamptz;not null" json:"updated_at"`
}

func (BrowserTabBinding) TableName() string { return "browser_tab_bindings" }

// BrowserTabBindingCaller is the authenticated browser-session tuple used to
// bind every document proof to one real browser session and subject.
type BrowserTabBindingCaller struct {
	SubjectUserID int64
	SessionID     string
}

// BrowserTabBindingCreate contains only digest material generated by the
// application. All expiries are absolute UTC bounds calculated by that owner.
type BrowserTabBindingCreate struct {
	Caller                 BrowserTabBindingCaller
	ResumeNonceDigest      []byte
	DocumentProofDigest    []byte
	ReloadTokenDigest      []byte
	DocumentLeaseExpiresAt time.Time
	BindingExpiresAt       time.Time
}

// BrowserTabBindingCopyCreate creates a distinct binding for an explicit copied
// browser pair. A non-collision result is a fresh, unselected binding.
type BrowserTabBindingCopyCreate struct {
	Create                  BrowserTabBindingCreate
	CopiedTabBindingID      string
	CopiedResumeNonceDigest []byte
}

// BrowserTabBindingResume atomically consumes the current reload token and
// replaces only the old document proof/lease. Its pin is deliberately absent.
type BrowserTabBindingResume struct {
	Caller                 BrowserTabBindingCaller
	TabBindingID           string
	ResumeNonceDigest      []byte
	ReloadTokenDigest      []byte
	NewDocumentProofDigest []byte
	NewReloadTokenDigest   []byte
	DocumentLeaseExpiresAt time.Time
}

// BrowserTabBindingGuard is the binding ID plus current document proof supplied
// by every binding-bound request and lease operation.
type BrowserTabBindingGuard struct {
	Caller              BrowserTabBindingCaller
	TabBindingID        string
	DocumentProofDigest []byte
}

// BrowserTabBindingLease renews or closes exactly the guarded document lease.
type BrowserTabBindingLease struct {
	BrowserTabBindingGuard
	DocumentLeaseExpiresAt time.Time
}

// BrowserTabBindingContext is the persisted exact UCI ContextRef projection.
// UCI remains responsible for validating it before a caller can pin it.
type BrowserTabBindingContext struct {
	SourceID          string
	CheckoutID        string
	ViewID            string
	AnalysisProfileID string
	Generation        int64
}

// BrowserTabBindingPin stores an already-authorized exact context after the
// same binding/proof guard used for ordinary binding-bound operations.
type BrowserTabBindingPin struct {
	BrowserTabBindingGuard
	Context BrowserTabBindingContext
}

// BrowserTabBindingStore is the sole persistence owner for browser tab binding
// state. It neither reads nor writes browser grants or UCI authorization state.
type BrowserTabBindingStore struct {
	db *gorm.DB
}

// NewBrowserTabBindingStore creates a binding store backed by db.
func NewBrowserTabBindingStore(db *gorm.DB) *BrowserTabBindingStore {
	return &BrowserTabBindingStore{db: db}
}

// Create creates a fresh, unselected binding with a server-generated opaque ID.
func (s *BrowserTabBindingStore) Create(ctx context.Context, in BrowserTabBindingCreate) (BrowserTabBinding, error) {
	if err := validateBrowserTabBindingCreate(ctx, in); err != nil {
		return BrowserTabBinding{}, err
	}
	if err := s.requireDB("create"); err != nil {
		return BrowserTabBinding{}, err
	}

	var binding BrowserTabBinding
	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now, err := browserTabBindingDatabaseClock(ctx, tx)
		if err != nil {
			return err
		}
		binding = newBrowserTabBinding(in, now)
		if err := tx.WithContext(ctx).Create(&binding).Error; err != nil {
			return fmt.Errorf("browser tab binding create: %w", err)
		}
		return nil
	})
	if err != nil {
		return BrowserTabBinding{}, err
	}
	return cloneBrowserTabBinding(binding), nil
}

// CreateFromCopy creates a fresh unselected binding for the requesting document.
// collision is true only when the supplied pair names an existing unexpired
// binding of the same browser session and subject; that original row is never
// modified by this transition.
func (s *BrowserTabBindingStore) CreateFromCopy(ctx context.Context, in BrowserTabBindingCopyCreate) (binding BrowserTabBinding, collision bool, err error) {
	if err := validateBrowserTabBindingCreate(ctx, in.Create); err != nil {
		return BrowserTabBinding{}, false, err
	}
	if err := s.requireDB("create from copy"); err != nil {
		return BrowserTabBinding{}, false, err
	}
	if !validBrowserTabBindingID(in.CopiedTabBindingID) || !validBrowserTabBindingDigest(in.CopiedResumeNonceDigest) {
		return BrowserTabBinding{}, false, ErrBrowserTabBindingDenied
	}

	err = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now, clockErr := browserTabBindingDatabaseClock(ctx, tx)
		if clockErr != nil {
			return clockErr
		}
		var original BrowserTabBinding
		lookup := tx.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Where("tab_binding_id = ?", in.CopiedTabBindingID).First(&original)
		if lookup.Error != nil && !errors.Is(lookup.Error, gorm.ErrRecordNotFound) {
			return fmt.Errorf("browser tab binding copy lookup: %w", lookup.Error)
		}
		if lookup.Error == nil && !original.BindingExpiresAt.After(now) {
			if err := tx.WithContext(ctx).Where("tab_binding_id = ?", original.TabBindingID).Delete(&BrowserTabBinding{}).Error; err != nil {
				return fmt.Errorf("browser tab binding expire copied binding: %w", err)
			}
		}
		if lookup.Error == nil && original.BindingExpiresAt.After(now) &&
			original.SubjectUserID == in.Create.Caller.SubjectUserID && original.SessionID == in.Create.Caller.SessionID &&
			bytes.Equal(original.ResumeNonceDigest, in.CopiedResumeNonceDigest) {
			collision = true
		}
		binding = newBrowserTabBinding(in.Create, now)
		if err := tx.WithContext(ctx).Create(&binding).Error; err != nil {
			return fmt.Errorf("browser tab binding create from copy: %w", err)
		}
		return nil
	})
	if err != nil {
		return BrowserTabBinding{}, false, err
	}
	return cloneBrowserTabBinding(binding), collision, nil
}

// Resume consumes the current one-time reload token only after the prior live
// document is closed or its lease has expired. A pending reload leaves every
// original field intact so the same material can be retried after that point.
func (s *BrowserTabBindingStore) Resume(ctx context.Context, in BrowserTabBindingResume) (binding BrowserTabBinding, state BrowserTabBindingResumeState, err error) {
	if err := validateBrowserTabBindingResume(ctx, in); err != nil {
		return BrowserTabBinding{}, "", err
	}
	if err := s.requireDB("resume"); err != nil {
		return BrowserTabBinding{}, "", err
	}

	denied := false
	err = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now, clockErr := browserTabBindingDatabaseClock(ctx, tx)
		if clockErr != nil {
			return clockErr
		}
		binding, denied, err = s.lockBindingForCaller(ctx, tx, in.TabBindingID, in.Caller, now)
		if err != nil || denied {
			return err
		}
		if !bytes.Equal(binding.ResumeNonceDigest, in.ResumeNonceDigest) || !bytes.Equal(binding.ReloadTokenDigest, in.ReloadTokenDigest) {
			denied = true
			return nil
		}
		if binding.DocumentLeaseState == BrowserTabBindingLeaseLive && !binding.DocumentLeaseExpiresAt.After(now) {
			if err := tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
				"document_lease_state": BrowserTabBindingLeaseExpired,
				"updated_at":           now,
			}).Error; err != nil {
				return fmt.Errorf("browser tab binding expire document lease: %w", err)
			}
			binding.DocumentLeaseState = BrowserTabBindingLeaseExpired
		}
		if binding.DocumentLeaseState == BrowserTabBindingLeaseLive {
			state = BrowserTabBindingReloadPending
			return nil
		}
		if binding.DocumentLeaseState != BrowserTabBindingLeaseClosed && binding.DocumentLeaseState != BrowserTabBindingLeaseExpired {
			denied = true
			return nil
		}
		if err := tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
			"document_proof_digest":     cloneBrowserTabBindingDigest(in.NewDocumentProofDigest),
			"reload_token_digest":       cloneBrowserTabBindingDigest(in.NewReloadTokenDigest),
			"document_lease_state":      BrowserTabBindingLeaseLive,
			"document_lease_expires_at": in.DocumentLeaseExpiresAt.UTC(),
			"updated_at":                now,
		}).Error; err != nil {
			return fmt.Errorf("browser tab binding resume: %w", err)
		}
		binding.DocumentProofDigest = cloneBrowserTabBindingDigest(in.NewDocumentProofDigest)
		binding.ReloadTokenDigest = cloneBrowserTabBindingDigest(in.NewReloadTokenDigest)
		binding.DocumentLeaseState = BrowserTabBindingLeaseLive
		binding.DocumentLeaseExpiresAt = in.DocumentLeaseExpiresAt.UTC()
		binding.UpdatedAt = now
		state = BrowserTabBindingResumed
		return nil
	})
	if err != nil {
		return BrowserTabBinding{}, "", err
	}
	if denied {
		return BrowserTabBinding{}, "", ErrBrowserTabBindingDenied
	}
	return cloneBrowserTabBinding(binding), state, nil
}

// Guard validates the caller, binding ID, and current document proof before any
// binding-bound operation. It durably marks a lapsed live lease expired while
// retaining its binding and pin, then refuses the stale proof.
func (s *BrowserTabBindingStore) Guard(ctx context.Context, in BrowserTabBindingGuard) (binding BrowserTabBinding, err error) {
	if err := validateBrowserTabBindingGuard(ctx, in); err != nil {
		return BrowserTabBinding{}, err
	}
	if err := s.requireDB("guard"); err != nil {
		return BrowserTabBinding{}, err
	}
	denied := false
	err = s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now, clockErr := browserTabBindingDatabaseClock(ctx, tx)
		if clockErr != nil {
			return clockErr
		}
		binding, denied, err = s.lockBindingForCaller(ctx, tx, in.TabBindingID, in.Caller, now)
		if err != nil || denied {
			return err
		}
		if binding.DocumentLeaseState == BrowserTabBindingLeaseLive && !binding.DocumentLeaseExpiresAt.After(now) {
			if err := tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
				"document_lease_state": BrowserTabBindingLeaseExpired,
				"updated_at":           now,
			}).Error; err != nil {
				return fmt.Errorf("browser tab binding expire stale lease: %w", err)
			}
			denied = true
			return nil
		}
		if binding.DocumentLeaseState != BrowserTabBindingLeaseLive || !bytes.Equal(binding.DocumentProofDigest, in.DocumentProofDigest) {
			denied = true
			return nil
		}
		return nil
	})
	if err != nil {
		return BrowserTabBinding{}, err
	}
	if denied {
		return BrowserTabBinding{}, ErrBrowserTabBindingDenied
	}
	return cloneBrowserTabBinding(binding), nil
}

// Renew extends only the current guarded document lease.
func (s *BrowserTabBindingStore) Renew(ctx context.Context, in BrowserTabBindingLease) error {
	if err := validateBrowserTabBindingLease(ctx, in, true); err != nil {
		return err
	}
	return s.mutateLiveLease(ctx, in.BrowserTabBindingGuard, func(tx *gorm.DB, binding BrowserTabBinding, now time.Time) error {
		return tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
			"document_lease_expires_at": in.DocumentLeaseExpiresAt.UTC(),
			"updated_at":                now,
		}).Error
	})
}

// Close acknowledges the current document and makes its binding immediately
// eligible for the normal reload-resume transition.
func (s *BrowserTabBindingStore) Close(ctx context.Context, in BrowserTabBindingLease) error {
	if err := validateBrowserTabBindingLease(ctx, in, false); err != nil {
		return err
	}
	return s.mutateLiveLease(ctx, in.BrowserTabBindingGuard, func(tx *gorm.DB, binding BrowserTabBinding, now time.Time) error {
		return tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
			"document_lease_state":      BrowserTabBindingLeaseClosed,
			"document_lease_expires_at": now,
			"updated_at":                now,
		}).Error
	})
}

// Pin stores an already-authorized exact UCI ContextRef only for the currently
// guarded document. It neither checks nor creates a browser read grant.
func (s *BrowserTabBindingStore) Pin(ctx context.Context, in BrowserTabBindingPin) error {
	if err := validateBrowserTabBindingContext(in.Context); err != nil {
		return err
	}
	if err := validateBrowserTabBindingGuard(ctx, in.BrowserTabBindingGuard); err != nil {
		return err
	}
	return s.mutateLiveLease(ctx, in.BrowserTabBindingGuard, func(tx *gorm.DB, binding BrowserTabBinding, now time.Time) error {
		return tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
			"pinned_source_id":           in.Context.SourceID,
			"pinned_checkout_id":         in.Context.CheckoutID,
			"pinned_view_id":             in.Context.ViewID,
			"pinned_analysis_profile_id": in.Context.AnalysisProfileID,
			"pinned_generation":          in.Context.Generation,
			"updated_at":                 now,
		}).Error
	})
}

// DestroySession clears every binding, pin, proof digest, and resume digest for
// a browser session when it ends. It intentionally never touches grants.
func (s *BrowserTabBindingStore) DestroySession(ctx context.Context, sessionID string) error {
	if err := validateBrowserTabBindingContextRequest(ctx); err != nil {
		return err
	}
	if !validBrowserTabBindingText(sessionID) {
		return ErrBrowserTabBindingDenied
	}
	if err := s.requireDB("destroy session"); err != nil {
		return err
	}
	if err := s.db.WithContext(ctx).Where("session_id = ?", sessionID).Delete(&BrowserTabBinding{}).Error; err != nil {
		return fmt.Errorf("browser tab binding destroy session: %w", err)
	}
	return nil
}

func (s *BrowserTabBindingStore) mutateLiveLease(ctx context.Context, guard BrowserTabBindingGuard, mutate func(*gorm.DB, BrowserTabBinding, time.Time) error) error {
	if err := s.requireDB("lease"); err != nil {
		return err
	}
	denied := false
	err := s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		now, clockErr := browserTabBindingDatabaseClock(ctx, tx)
		if clockErr != nil {
			return clockErr
		}
		binding, bindingDenied, bindingErr := s.lockBindingForCaller(ctx, tx, guard.TabBindingID, guard.Caller, now)
		if bindingErr != nil {
			return bindingErr
		}
		if bindingDenied {
			denied = true
			return nil
		}
		if binding.DocumentLeaseState == BrowserTabBindingLeaseLive && !binding.DocumentLeaseExpiresAt.After(now) {
			if err := tx.WithContext(ctx).Model(&BrowserTabBinding{}).Where("tab_binding_id = ?", binding.TabBindingID).Updates(map[string]any{
				"document_lease_state": BrowserTabBindingLeaseExpired,
				"updated_at":           now,
			}).Error; err != nil {
				return fmt.Errorf("browser tab binding expire lease: %w", err)
			}
			denied = true
			return nil
		}
		if binding.DocumentLeaseState != BrowserTabBindingLeaseLive || !bytes.Equal(binding.DocumentProofDigest, guard.DocumentProofDigest) {
			denied = true
			return nil
		}
		if err := mutate(tx, binding, now); err != nil {
			return fmt.Errorf("browser tab binding lease mutate: %w", err)
		}
		return nil
	})
	if err != nil {
		return err
	}
	if denied {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func (s *BrowserTabBindingStore) lockBindingForCaller(ctx context.Context, tx *gorm.DB, bindingID string, caller BrowserTabBindingCaller, now time.Time) (BrowserTabBinding, bool, error) {
	var binding BrowserTabBinding
	result := tx.WithContext(ctx).Clauses(clause.Locking{Strength: "UPDATE"}).Where("tab_binding_id = ?", bindingID).First(&binding)
	if errors.Is(result.Error, gorm.ErrRecordNotFound) {
		return BrowserTabBinding{}, true, nil
	}
	if result.Error != nil {
		return BrowserTabBinding{}, false, fmt.Errorf("browser tab binding lookup: %w", result.Error)
	}
	if !binding.BindingExpiresAt.After(now) {
		if err := tx.WithContext(ctx).Where("tab_binding_id = ?", binding.TabBindingID).Delete(&BrowserTabBinding{}).Error; err != nil {
			return BrowserTabBinding{}, false, fmt.Errorf("browser tab binding expire: %w", err)
		}
		return BrowserTabBinding{}, true, nil
	}
	if binding.SubjectUserID != caller.SubjectUserID || binding.SessionID != caller.SessionID {
		return BrowserTabBinding{}, true, nil
	}
	return binding, false, nil
}

func newBrowserTabBinding(in BrowserTabBindingCreate, now time.Time) BrowserTabBinding {
	return BrowserTabBinding{
		TabBindingID:           uuid.NewString(),
		SubjectUserID:          in.Caller.SubjectUserID,
		SessionID:              in.Caller.SessionID,
		ResumeNonceDigest:      cloneBrowserTabBindingDigest(in.ResumeNonceDigest),
		DocumentProofDigest:    cloneBrowserTabBindingDigest(in.DocumentProofDigest),
		ReloadTokenDigest:      cloneBrowserTabBindingDigest(in.ReloadTokenDigest),
		DocumentLeaseState:     BrowserTabBindingLeaseLive,
		DocumentLeaseExpiresAt: in.DocumentLeaseExpiresAt.UTC(),
		BindingExpiresAt:       in.BindingExpiresAt.UTC(),
		CreatedAt:              now,
		UpdatedAt:              now,
	}
}

func cloneBrowserTabBinding(binding BrowserTabBinding) BrowserTabBinding {
	copy := binding
	copy.ResumeNonceDigest = cloneBrowserTabBindingDigest(binding.ResumeNonceDigest)
	copy.DocumentProofDigest = cloneBrowserTabBindingDigest(binding.DocumentProofDigest)
	copy.ReloadTokenDigest = cloneBrowserTabBindingDigest(binding.ReloadTokenDigest)
	copy.PinnedSourceID = copyBrowserTabBindingString(binding.PinnedSourceID)
	copy.PinnedCheckoutID = copyBrowserTabBindingString(binding.PinnedCheckoutID)
	copy.PinnedViewID = copyBrowserTabBindingString(binding.PinnedViewID)
	copy.PinnedAnalysisProfileID = copyBrowserTabBindingString(binding.PinnedAnalysisProfileID)
	if binding.PinnedGeneration != nil {
		generation := *binding.PinnedGeneration
		copy.PinnedGeneration = &generation
	}
	return copy
}

func cloneBrowserTabBindingDigest(value []byte) []byte {
	return append([]byte(nil), value...)
}

func copyBrowserTabBindingString(value *string) *string {
	if value == nil {
		return nil
	}
	copy := *value
	return &copy
}

func (s *BrowserTabBindingStore) requireDB(operation string) error {
	if s == nil || s.db == nil {
		return fmt.Errorf("browser tab binding %s: %w", operation, errBrowserTabBindingStoreNotConfigured)
	}
	return nil
}

func validateBrowserTabBindingCreate(ctx context.Context, in BrowserTabBindingCreate) error {
	if err := validateBrowserTabBindingContextRequest(ctx); err != nil {
		return err
	}
	if !validBrowserTabBindingCaller(in.Caller) ||
		!validBrowserTabBindingDigest(in.ResumeNonceDigest) || !validBrowserTabBindingDigest(in.DocumentProofDigest) || !validBrowserTabBindingDigest(in.ReloadTokenDigest) ||
		!in.DocumentLeaseExpiresAt.After(time.Now().UTC()) || !in.BindingExpiresAt.After(in.DocumentLeaseExpiresAt) {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func validateBrowserTabBindingResume(ctx context.Context, in BrowserTabBindingResume) error {
	if err := validateBrowserTabBindingContextRequest(ctx); err != nil {
		return err
	}
	if !validBrowserTabBindingCaller(in.Caller) || !validBrowserTabBindingID(in.TabBindingID) ||
		!validBrowserTabBindingDigest(in.ResumeNonceDigest) || !validBrowserTabBindingDigest(in.ReloadTokenDigest) ||
		!validBrowserTabBindingDigest(in.NewDocumentProofDigest) || !validBrowserTabBindingDigest(in.NewReloadTokenDigest) ||
		!in.DocumentLeaseExpiresAt.After(time.Now().UTC()) {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func validateBrowserTabBindingGuard(ctx context.Context, in BrowserTabBindingGuard) error {
	if err := validateBrowserTabBindingContextRequest(ctx); err != nil {
		return err
	}
	if !validBrowserTabBindingCaller(in.Caller) || !validBrowserTabBindingID(in.TabBindingID) || !validBrowserTabBindingDigest(in.DocumentProofDigest) {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func validateBrowserTabBindingLease(ctx context.Context, in BrowserTabBindingLease, renew bool) error {
	if err := validateBrowserTabBindingGuard(ctx, in.BrowserTabBindingGuard); err != nil {
		return err
	}
	if renew && !in.DocumentLeaseExpiresAt.After(time.Now().UTC()) {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func validateBrowserTabBindingContext(context BrowserTabBindingContext) error {
	if validateUCIUUID("pinned_source_id", context.SourceID) != nil ||
		validateUCIUUID("pinned_checkout_id", context.CheckoutID) != nil ||
		validateUCIUUID("pinned_view_id", context.ViewID) != nil ||
		validateUCIUUID("pinned_analysis_profile_id", context.AnalysisProfileID) != nil ||
		context.Generation <= 0 {
		return ErrBrowserTabBindingDenied
	}
	return nil
}

func validateBrowserTabBindingContextRequest(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("browser tab binding: context is required")
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	return nil
}

func validBrowserTabBindingCaller(caller BrowserTabBindingCaller) bool {
	return caller.SubjectUserID > 0 && validBrowserTabBindingText(caller.SessionID)
}

func validBrowserTabBindingID(value string) bool {
	parsed, err := uuid.Parse(value)
	return err == nil && parsed != uuid.Nil && parsed.String() == value
}

func validBrowserTabBindingDigest(value []byte) bool {
	return len(value) == 32
}

func validBrowserTabBindingText(value string) bool {
	return value != "" && value == strings.TrimSpace(value) && !strings.ContainsAny(value, "\x00\r\n")
}

func browserTabBindingDatabaseClock(ctx context.Context, db *gorm.DB) (time.Time, error) {
	var now time.Time
	if err := db.WithContext(ctx).Raw("SELECT clock_timestamp()").Scan(&now).Error; err != nil {
		return time.Time{}, fmt.Errorf("browser tab binding database clock: %w", err)
	}
	return now.UTC(), nil
}
