// Package gorm provides GORM-based database operations for engram.
package gorm

import (
	"context"
	"fmt"
	"time"

	"gorm.io/gorm"
)

// Version source constants for ObservationVersion.Source.
const (
	// VersionSourceOriginal is the source value for the original observation narrative.
	VersionSourceOriginal = "original"
	// VersionSourceAPORewrite is the source value for LLM-rewritten narratives generated by APO-lite.
	VersionSourceAPORewrite = "apo_rewrite"
)

// ObservationVersion stores an alternative narrative for an observation,
// used by APO-lite (closed-loop learning Phase 5) to A/B test LLM-rewritten guidance.
type ObservationVersion struct {
	ID            int64     `gorm:"primaryKey"`
	ObservationID int64     `gorm:"column:observation_id;index"`
	Version       int       `gorm:"column:version"`
	Narrative     string    `gorm:"column:narrative"`
	IsActive      bool      `gorm:"column:is_active"`
	CreatedAt     time.Time `gorm:"column:created_at"`
	Source        string    `gorm:"column:source"` // "original" or "apo_rewrite"
}

// TableName returns the database table name.
func (ObservationVersion) TableName() string {
	return "observation_versions"
}

// VersionStore handles CRUD for observation_versions.
type VersionStore struct {
	db *gorm.DB
}

// NewVersionStore creates a new VersionStore.
func NewVersionStore(db *gorm.DB) *VersionStore {
	return &VersionStore{db: db}
}

// CreateVersion inserts a new version for the given observation and returns its ID.
// The new version is set to is_active=true by default. To use this as an A/B variant
// without immediately activating it, call SetActiveVersion afterward.
func (s *VersionStore) CreateVersion(ctx context.Context, obsID int64, narrative string, source string) (int64, error) {
	// Determine the next version number for this observation.
	var maxVersion int
	row := s.db.WithContext(ctx).
		Raw("SELECT COALESCE(MAX(version), 0) FROM observation_versions WHERE observation_id = ?", obsID).
		Row()
	if err := row.Scan(&maxVersion); err != nil {
		return 0, fmt.Errorf("fetch max version for observation %d: %w", obsID, err)
	}

	v := &ObservationVersion{
		ObservationID: obsID,
		Version:       maxVersion + 1,
		Narrative:     narrative,
		IsActive:      true,
		Source:        source,
	}

	if err := s.db.WithContext(ctx).Create(v).Error; err != nil {
		return 0, fmt.Errorf("create observation version for observation %d: %w", obsID, err)
	}

	return v.ID, nil
}

// GetActiveVersion returns the active version for the given observation, or nil if none exists.
func (s *VersionStore) GetActiveVersion(ctx context.Context, obsID int64) (*ObservationVersion, error) {
	var v ObservationVersion
	err := s.db.WithContext(ctx).
		Where("observation_id = ? AND is_active = TRUE", obsID).
		First(&v).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil
		}
		return nil, fmt.Errorf("get active version for observation %d: %w", obsID, err)
	}

	return &v, nil
}

// SetActiveVersion sets is_active=true for the given version and is_active=false for
// all other versions of the same observation. This is an atomic swap.
func (s *VersionStore) SetActiveVersion(ctx context.Context, obsID int64, versionID int64) error {
	return s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// Deactivate all versions for this observation.
		if err := tx.Exec(
			"UPDATE observation_versions SET is_active = FALSE WHERE observation_id = ?",
			obsID,
		).Error; err != nil {
			return fmt.Errorf("deactivate versions for observation %d: %w", obsID, err)
		}

		// Activate the requested version.
		result := tx.Exec(
			"UPDATE observation_versions SET is_active = TRUE WHERE id = ? AND observation_id = ?",
			versionID, obsID,
		)
		if result.Error != nil {
			return fmt.Errorf("activate version %d for observation %d: %w", versionID, obsID, result.Error)
		}
		if result.RowsAffected == 0 {
			return fmt.Errorf("version %d not found for observation %d", versionID, obsID)
		}

		return nil
	})
}

// GetVersions returns all versions for the given observation, ordered by version number ascending.
func (s *VersionStore) GetVersions(ctx context.Context, obsID int64) ([]ObservationVersion, error) {
	var versions []ObservationVersion
	err := s.db.WithContext(ctx).
		Where("observation_id = ?", obsID).
		Order("version ASC").
		Find(&versions).Error
	if err != nil {
		return nil, fmt.Errorf("get versions for observation %d: %w", obsID, err)
	}

	return versions, nil
}
