// Package worker provides session-related HTTP handlers.
package worker

import (
	"compress/gzip"
	"context"
	"database/sql"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/thebtf/engram/internal/sessions"
	gormdb "github.com/thebtf/engram/internal/db/gorm"
	"github.com/thebtf/engram/internal/learning"
	"github.com/thebtf/engram/internal/privacy"
	"github.com/thebtf/engram/internal/worker/session"
	"github.com/thebtf/engram/pkg/models"
	"github.com/rs/zerolog/log"
)

// SessionInitRequest is the request body for session initialization.
type SessionInitRequest struct {
	ClaudeSessionID     string `json:"claudeSessionId"`
	Project             string `json:"project"`
	Prompt              string `json:"prompt"`
	MatchedObservations int    `json:"matchedObservations"`
}

// SessionInitResponse is the response for session initialization.
type SessionInitResponse struct {
	Reason       string `json:"reason,omitempty"`
	SessionDBID  int64  `json:"sessionDbId"`
	PromptNumber int    `json:"promptNumber"`
	Skipped      bool   `json:"skipped,omitempty"`
}

// DuplicatePromptWindowSeconds is the time window for detecting duplicate prompt submissions.
// If the same prompt text is seen within this window, it's considered a duplicate hook invocation.
const DuplicatePromptWindowSeconds = 10

// internalPromptSignatures contains substrings that identify internal system prompts
// which should be rejected server-side. These prompts are generated by the engram system
// itself (e.g., memory extraction agents) and should not be stored as user prompts.
var internalPromptSignatures = []string{
	"You are a memory extraction agent for Claude Code sessions",
	"You are a session summarization agent",
	"Extract meaningful observations from the following",
}

// isInternalPrompt checks if the prompt text contains known system prompt signatures.
func isInternalPrompt(prompt string) bool {
	for _, sig := range internalPromptSignatures {
		if strings.Contains(prompt, sig) {
			return true
		}
	}
	return false
}

// handleSessionInit godoc
// @Summary Initialize session from user-prompt hook
// @Description Handles session initialization from user-prompt hook. Idempotent — duplicate requests within a short time window return existing prompt data.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param body body SessionInitRequest true "Session init params"
// @Success 200 {object} SessionInitResponse
// @Failure 400 {string} string "bad request"
// @Failure 500 {string} string "internal error"
// @Router /api/sessions/init [post]
func (s *Service) handleSessionInit(w http.ResponseWriter, r *http.Request) {
	var req SessionInitRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Internal prompt detection: reject prompts containing system prompt signatures
	if isInternalPrompt(req.Prompt) {
		log.Debug().
			Str("project", req.Project).
			Msg("Rejecting session init with internal system prompt")
		writeJSON(w, SessionInitResponse{
			Skipped: true,
			Reason:  "internal",
		})
		return
	}

	// Privacy check
	if privacy.IsEntirelyPrivate(req.Prompt) {
		// Create session but skip processing
		sessionID, _ := s.sessionStore.CreateSDKSession(r.Context(), req.ClaudeSessionID, req.Project, "")
		promptNum, _ := s.sessionStore.IncrementPromptCounter(r.Context(), sessionID)

		writeJSON(w, SessionInitResponse{
			SessionDBID:  sessionID,
			PromptNumber: promptNum,
			Skipped:      true,
			Reason:       "private",
		})
		return
	}

	// Clean prompt
	cleanedPrompt := privacy.Clean(req.Prompt)

	// DUPLICATE DETECTION: Check if this exact prompt was already saved recently.
	// This prevents the bug where the hook fires multiple times for the same user action,
	// creating many duplicate prompts with incrementing numbers.
	if existingID, existingNum, found := s.promptStore.FindRecentPromptByText(r.Context(), req.ClaudeSessionID, cleanedPrompt, DuplicatePromptWindowSeconds); found {
		// Get or create session (idempotent)
		sessionID, _ := s.sessionStore.CreateSDKSession(r.Context(), req.ClaudeSessionID, req.Project, cleanedPrompt)

		log.Debug().
			Int64("sessionId", sessionID).
			Int("promptNumber", existingNum).
			Int64("promptId", existingID).
			Msg("Duplicate prompt detected - returning existing")

		// Return existing prompt data without incrementing or saving again
		writeJSON(w, SessionInitResponse{
			SessionDBID:  sessionID,
			PromptNumber: existingNum,
		})
		return
	}

	// CROSS-SESSION DUPLICATE DETECTION: Check across ALL sessions.
	// When hooks fire from different session IDs (e.g., subagent spawning),
	// the same prompt text may appear under a different claude_session_id.
	if existingID, existingNum, found := s.promptStore.FindRecentPromptByTextGlobal(r.Context(), cleanedPrompt, DuplicatePromptWindowSeconds); found {
		sessionID, _ := s.sessionStore.CreateSDKSession(r.Context(), req.ClaudeSessionID, req.Project, cleanedPrompt)

		log.Debug().
			Int64("sessionId", sessionID).
			Int("promptNumber", existingNum).
			Int64("promptId", existingID).
			Msg("Cross-session duplicate prompt detected - returning existing")

		writeJSON(w, SessionInitResponse{
			SessionDBID:  sessionID,
			PromptNumber: existingNum,
			Skipped:      true,
			Reason:       "cross-session-duplicate",
		})
		return
	}

	// Create session (idempotent)
	sessionID, err := s.sessionStore.CreateSDKSession(r.Context(), req.ClaudeSessionID, req.Project, cleanedPrompt)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Increment prompt counter
	promptNum, err := s.sessionStore.IncrementPromptCounter(r.Context(), sessionID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Save user prompt with matched observation count
	promptID, err := s.promptStore.SaveUserPromptWithMatches(r.Context(), req.ClaudeSessionID, promptNum, cleanedPrompt, req.MatchedObservations)
	if err != nil {
		log.Warn().Err(err).Msg("Failed to save user prompt")
		// Non-fatal: continue with session initialization
	} else if s.vectorSync != nil {
		// Sync to vector DB asynchronously (non-blocking)
		now := time.Now()
		promptWithSession := &models.UserPromptWithSession{
			UserPrompt: models.UserPrompt{
				ID:                  promptID,
				ClaudeSessionID:     req.ClaudeSessionID,
				PromptNumber:        promptNum,
				PromptText:          cleanedPrompt,
				MatchedObservations: req.MatchedObservations,
				CreatedAt:           now.Format(time.RFC3339),
				CreatedAtEpoch:      now.UnixMilli(),
			},
			Project:      req.Project,
			SDKSessionID: req.ClaudeSessionID,
		}
		s.asyncVectorSync(func() {
			// Use service context as parent to respect shutdown signals
			ctx, cancel := context.WithTimeout(s.ctx, 30*time.Second)
			defer cancel()
			if err := s.vectorSync.SyncUserPrompt(ctx, promptWithSession); err != nil {
				if s.ctx.Err() == nil { // Don't log during shutdown
					log.Warn().Err(err).Int64("id", promptID).Msg("Failed to sync user prompt to vector store")
				}
			}
		})
	}

	log.Info().
		Int64("sessionId", sessionID).
		Int("promptNumber", promptNum).
		Str("project", req.Project).
		Msg("Session initialized")

	// Broadcast prompt event for dashboard refresh
	s.sseBroadcaster.Broadcast(map[string]any{
		"type":    "prompt",
		"action":  "created",
		"project": req.Project,
	})

	writeJSON(w, SessionInitResponse{
		SessionDBID:  sessionID,
		PromptNumber: promptNum,
	})
}

// SessionStartRequest is the request body for starting SDK agent.
type SessionStartRequest struct {
	UserPrompt   string `json:"userPrompt"`
	PromptNumber int    `json:"promptNumber"`
}

// handleSessionStart godoc
// @Summary Start SDK agent session
// @Description Initializes an SDK agent session in the session manager. Observations are processed asynchronously.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Session database ID"
// @Param body body SessionStartRequest true "Session start params"
// @Success 200 "OK"
// @Failure 400 {string} string "invalid session id"
// @Failure 404 {string} string "session not found"
// @Failure 500 {string} string "internal error"
// @Router /sessions/{id}/init [post]
func (s *Service) handleSessionStart(w http.ResponseWriter, r *http.Request) {
	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid session id", http.StatusBadRequest)
		return
	}

	var req SessionStartRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Initialize session in manager
	sess, err := s.sessionManager.InitializeSession(r.Context(), id, req.UserPrompt, req.PromptNumber)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if sess == nil {
		http.Error(w, "session not found", http.StatusNotFound)
		return
	}

	// Session is now registered. Observations will be processed
	// asynchronously by the background queue processor (processQueue in service.go).
	log.Info().
		Int64("sessionId", id).
		Int("promptNumber", req.PromptNumber).
		Msg("SDK agent session initialized")

	s.broadcastProcessingStatus()
	w.WriteHeader(http.StatusOK)
}

// ObservationRequest is the request body for posting observations.
type ObservationRequest struct {
	ClaudeSessionID string `json:"claudeSessionId"`
	Project         string `json:"project"`
	ToolName        string `json:"tool_name"`
	ToolInput       any    `json:"tool_input"`
	ToolResponse    any    `json:"tool_response"`
	CWD             string `json:"cwd"`
}

// handleObservation godoc
// @Summary Post observation from hook
// @Description Handles observation posting from post-tool-use hook. Creates session on-the-fly if not found.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param body body ObservationRequest true "Observation data"
// @Success 200 "OK"
// @Failure 400 {string} string "bad request"
// @Failure 500 {string} string "internal error"
// @Router /api/sessions/observations [post]
func (s *Service) handleObservation(w http.ResponseWriter, r *http.Request) {
	var req ObservationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Find session
	sess, err := s.sessionStore.FindAnySDKSession(r.Context(), req.ClaudeSessionID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if sess == nil {
		// Create session on-the-fly with project from request
		id, err := s.sessionStore.CreateSDKSession(r.Context(), req.ClaudeSessionID, req.Project, "")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		sess, _ = s.sessionStore.GetSessionByID(r.Context(), id)
	}

	// Queue observation
	if err := s.sessionManager.QueueObservation(r.Context(), sess.ID, session.ObservationData{
		ToolName:     req.ToolName,
		ToolInput:    req.ToolInput,
		ToolResponse: req.ToolResponse,
		CWD:          req.CWD,
	}); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	s.broadcastProcessingStatus()
	w.WriteHeader(http.StatusOK)
}

// SubagentCompleteRequest is the request body for subagent completion.
type SubagentCompleteRequest struct {
	ClaudeSessionID string `json:"claudeSessionId"`
	Project         string `json:"project"`
}

// handleSubagentComplete godoc
// @Summary Notify subagent completion
// @Description Handles subagent/Task completion notifications. Triggers immediate processing of any queued observations from the subagent.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param body body SubagentCompleteRequest true "Subagent completion data"
// @Success 200 "OK"
// @Failure 400 {string} string "bad request"
// @Router /api/sessions/subagent-complete [post]
func (s *Service) handleSubagentComplete(w http.ResponseWriter, r *http.Request) {
	var req SubagentCompleteRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Find session
	sess, err := s.sessionStore.FindAnySDKSession(r.Context(), req.ClaudeSessionID)
	if err != nil || sess == nil {
		// Session not found - subagent may have been in a different context
		log.Debug().
			Str("claudeSessionId", req.ClaudeSessionID).
			Msg("Subagent complete - no active session found")
		w.WriteHeader(http.StatusOK)
		return
	}

	// Trigger immediate processing of queued observations
	messages := s.sessionManager.DrainMessages(sess.ID)
	if len(messages) > 0 && s.processor != nil {
		log.Info().
			Int64("sessionId", sess.ID).
			Int("messages", len(messages)).
			Msg("Processing queued observations from subagent")

		for _, msg := range messages {
			if msg.Type == session.MessageTypeObservation && msg.Observation != nil {
				err := s.processor.ProcessObservation(
					context.Background(),
					sess.SDKSessionID.String,
					sess.Project,
					msg.Observation.ToolName,
					msg.Observation.ToolInput,
					msg.Observation.ToolResponse,
					msg.Observation.PromptNumber,
					msg.Observation.CWD,
				)
				if err != nil {
					log.Error().Err(err).
						Str("tool", msg.Observation.ToolName).
						Msg("Failed to process subagent observation")
				}
			}
		}
	}

	s.broadcastProcessingStatus()
	w.WriteHeader(http.StatusOK)
}

// handleGetSessionByClaudeID godoc
// @Summary Get session by Claude session ID
// @Description Looks up a session by its Claude session ID.
// @Tags Sessions
// @Produce json
// @Security ApiKeyAuth
// @Param claudeSessionId query string true "Claude session ID"
// @Success 200 {object} object
// @Failure 400 {string} string "claudeSessionId required"
// @Failure 404 {string} string "session not found"
// @Failure 500 {string} string "internal error"
// @Router /api/sessions [get]
func (s *Service) handleGetSessionByClaudeID(w http.ResponseWriter, r *http.Request) {
	claudeSessionID := r.URL.Query().Get("claudeSessionId")
	if claudeSessionID == "" {
		http.Error(w, "claudeSessionId required", http.StatusBadRequest)
		return
	}

	session, err := s.sessionStore.FindAnySDKSession(r.Context(), claudeSessionID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if session == nil {
		http.Error(w, "session not found", http.StatusNotFound)
		return
	}

	writeJSON(w, session)
}

// SummarizeRequest is the request body for summarize requests.
type SummarizeRequest struct {
	LastUserMessage      string `json:"lastUserMessage"`
	LastAssistantMessage string `json:"lastAssistantMessage"`
}

// handleSummarize godoc
// @Summary Summarize session
// @Description Handles summarize requests from the stop hook. Queues a summarization request for background processing.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Session database ID"
// @Param body body SummarizeRequest true "Last messages for summarization"
// @Success 200 "OK"
// @Failure 400 {string} string "invalid session id"
// @Failure 500 {string} string "internal error"
// @Router /sessions/{id}/summarize [post]
func (s *Service) handleSummarize(w http.ResponseWriter, r *http.Request) {
	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid session id", http.StatusBadRequest)
		return
	}

	var req SummarizeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Queue summarize request
	if err := s.sessionManager.QueueSummarize(r.Context(), id, req.LastUserMessage, req.LastAssistantMessage); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	s.broadcastProcessingStatus()
	w.WriteHeader(http.StatusOK)
}

// ExtractLearningsRequest is the request body for learning extraction.
type ExtractLearningsRequest struct {
	Messages []learning.Message `json:"messages"`
	Project  string             `json:"project"`
}

// handleExtractLearnings godoc
// @Summary Extract learnings from session
// @Description Runs LLM-based extraction of behavioral patterns from a session transcript and stores resulting guidance observations.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Session database ID"
// @Param body body ExtractLearningsRequest true "Session messages and project"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {string} string "invalid request body"
// @Failure 500 {string} string "extraction failed"
// @Failure 503 {string} string "service not ready"
// @Router /api/sessions/{id}/extract-learnings [post]
func (s *Service) handleExtractLearnings(w http.ResponseWriter, r *http.Request) {
	if !learning.IsEnabled() {
		writeJSON(w, map[string]any{"status": "disabled", "count": 0})
		return
	}

	var req ExtractLearningsRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	if len(req.Messages) == 0 {
		writeJSON(w, map[string]any{"status": "ok", "count": 0})
		return
	}

	s.initMu.RLock()
	observationStore := s.observationStore
	s.initMu.RUnlock()

	if observationStore == nil {
		http.Error(w, "service not ready", http.StatusServiceUnavailable)
		return
	}

	// Create LLM client
	llmCfg := learning.DefaultOpenAIConfig()
	llmClient := learning.NewOpenAIClient(llmCfg)
	if !llmClient.IsConfigured() {
		writeJSON(w, map[string]any{"status": "llm_not_configured", "count": 0})
		return
	}

	// Extract learnings
	extractor := learning.NewExtractor(llmClient)
	observations, err := extractor.ExtractGuidance(r.Context(), req.Messages, req.Project)
	if err != nil {
		log.Warn().Err(err).Msg("Learning extraction failed")
		http.Error(w, "extraction failed", http.StatusInternalServerError)
		return
	}

	if len(observations) == 0 {
		writeJSON(w, map[string]any{"status": "ok", "count": 0})
		return
	}

	// Store extracted observations
	stored := 0
	for _, obs := range observations {
		if _, _, err := observationStore.StoreObservation(r.Context(), "", req.Project, obs, 0, 0); err != nil {
			log.Warn().Err(err).Str("title", obs.Title).Msg("Failed to store extracted guidance")
			continue
		}
		stored++
	}

	log.Info().Int("extracted", len(observations)).Int("stored", stored).Msg("Learning extraction complete")

	writeJSON(w, map[string]any{
		"status": "ok",
		"count":  stored,
	})
}

// maxSessionIndexBody is the per-request body limit for session indexing (5 MB).
const maxSessionIndexBody = 5 * 1024 * 1024

// handleIndexSession godoc
// @Summary Index session transcript
// @Description Accepts a raw JSONL session transcript and indexes it. Supports gzip-compressed bodies.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param workstation_id query string true "Workstation ID"
// @Param session_id query string false "Override session ID"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {string} string "bad request"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "service not ready"
// @Router /api/sessions/index [post]
func (s *Service) handleIndexSession(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.sessionIdxStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "service not ready", http.StatusServiceUnavailable)
		return
	}

	workstationID := r.URL.Query().Get("workstation_id")
	if workstationID == "" {
		http.Error(w, "workstation_id query param required", http.StatusBadRequest)
		return
	}

	sessionIDOverride := r.URL.Query().Get("session_id")

	// Apply per-endpoint body limit.
	body := http.MaxBytesReader(w, r.Body, maxSessionIndexBody)
	defer func() { _ = body.Close() }()

	var reader io.Reader = body
	if r.Header.Get("Content-Encoding") == "gzip" {
		gz, err := gzip.NewReader(body)
		if err != nil {
			http.Error(w, "invalid gzip body", http.StatusBadRequest)
			return
		}
		defer func() { _ = gz.Close() }()
		// Limit the decompressed stream to prevent gzip bomb attacks;
		// the compressed-stream limit above only applies to the wire bytes.
		reader = io.LimitReader(gz, maxSessionIndexBody)
	}

	meta, err := sessions.ParseSessionReader(reader)
	if err != nil {
		// On body too large, ParseSessionReader may return a partial result.
		// We still attempt to index what was parsed.
		log.Warn().Err(err).Msg("Session parse error (may be partial)")
	}

	if meta == nil {
		http.Error(w, "failed to parse session", http.StatusBadRequest)
		return
	}

	// Override session ID from query param if provided (client knows the Claude session ID).
	if sessionIDOverride != "" {
		meta.SessionID = sessionIDOverride
	}
	if meta.SessionID == "" {
		http.Error(w, "session_id not found in transcript and not provided via query param", http.StatusBadRequest)
		return
	}

	// Build content from exchanges.
	parts := make([]string, 0, len(meta.Exchanges)*2)
	for _, exchange := range meta.Exchanges {
		parts = append(parts, exchange.UserText)
		parts = append(parts, exchange.AssistantText)
	}
	content := strings.Join(parts, "\n")

	counts := meta.ToolCounts
	if counts == nil {
		counts = make(map[string]int)
	}
	toolCounts, err := json.Marshal(counts)
	if err != nil {
		http.Error(w, "failed to marshal tool counts", http.StatusInternalServerError)
		return
	}

	projectID := ""
	if meta.ProjectPath != "" {
		projectID = sessions.ProjectID(meta.ProjectPath)
	}

	indexed := &gormdb.IndexedSession{
		ID:            meta.SessionID,
		WorkstationID: workstationID,
		ProjectID:     projectID,
		ProjectPath:   sql.NullString{String: meta.ProjectPath, Valid: meta.ProjectPath != ""},
		GitBranch:     sql.NullString{String: meta.GitBranch, Valid: meta.GitBranch != ""},
		FirstMsgAt:    sql.NullTime{Time: meta.FirstMsgAt, Valid: !meta.FirstMsgAt.IsZero()},
		LastMsgAt:     sql.NullTime{Time: meta.LastMsgAt, Valid: !meta.LastMsgAt.IsZero()},
		ExchangeCount: meta.ExchangeCount,
		ToolCounts:    sql.NullString{String: string(toolCounts), Valid: true},
		Content:       sql.NullString{String: content, Valid: content != ""},
		FileMtime:     sql.NullTime{Time: time.Now().UTC(), Valid: true},
	}

	if err := store.UpsertSession(r.Context(), indexed); err != nil {
		log.Error().Err(err).Str("session_id", meta.SessionID).Msg("Failed to upsert indexed session")
		http.Error(w, "failed to store session", http.StatusInternalServerError)
		return
	}

	status := "indexed"
	if meta.ExchangeCount == 0 && len(meta.Exchanges) == 0 {
		status = "empty"
	}

	log.Info().
		Str("session_id", meta.SessionID).
		Str("workstation_id", workstationID).
		Int("exchange_count", meta.ExchangeCount).
		Msg("Session indexed via REST API")

	writeJSON(w, map[string]any{
		"status":         status,
		"session_id":     meta.SessionID,
		"exchange_count": meta.ExchangeCount,
	})
}

// CheckSessionsRequest is the request body for checking which sessions are already indexed.
type CheckSessionsRequest struct {
	SessionIDs []string `json:"session_ids"`
}

// handleCheckSessions godoc
// @Summary Check which sessions are indexed
// @Description Returns which session IDs from the request are NOT yet indexed.
// @Tags Sessions
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param body body CheckSessionsRequest true "Session IDs to check"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {string} string "invalid request body"
// @Failure 500 {string} string "database error"
// @Failure 503 {string} string "service not ready"
// @Router /api/sessions/check [post]
func (s *Service) handleCheckSessions(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.sessionIdxStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "service not ready", http.StatusServiceUnavailable)
		return
	}

	var req CheckSessionsRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	if len(req.SessionIDs) == 0 {
		writeJSON(w, map[string]any{"missing": []string{}})
		return
	}

	existing, err := store.CheckSessionsExist(r.Context(), req.SessionIDs)
	if err != nil {
		log.Error().Err(err).Msg("Failed to check session existence")
		http.Error(w, "database error", http.StatusInternalServerError)
		return
	}

	existingSet := make(map[string]struct{}, len(existing))
	for _, id := range existing {
		existingSet[id] = struct{}{}
	}

	missing := make([]string, 0, len(req.SessionIDs))
	for _, id := range req.SessionIDs {
		if _, ok := existingSet[id]; !ok {
			missing = append(missing, id)
		}
	}

	writeJSON(w, map[string]any{"missing": missing})
}
