// Package worker provides the main worker service for engram.
package worker

import (
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/thebtf/engram/pkg/models"
)

// DefaultPatternsLimit is the default number of patterns to return.
const DefaultPatternsLimit = 100

// handleGetPatterns godoc
// @Summary List patterns
// @Description Returns all active patterns, optionally filtered by type or project.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param type query string false "Filter by pattern type"
// @Param project query string false "Filter by project"
// @Param limit query int false "Number of results (default 100)"
// @Success 200 {array} models.Pattern
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns [get]
func (s *Service) handleGetPatterns(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	// Parse query parameters
	limit := DefaultPatternsLimit
	if l := r.URL.Query().Get("limit"); l != "" {
		if parsed, err := strconv.Atoi(l); err == nil && parsed > 0 {
			limit = parsed
		}
	}

	offset := 0
	if o := r.URL.Query().Get("offset"); o != "" {
		if parsed, err := strconv.Atoi(o); err == nil && parsed >= 0 {
			offset = parsed
		}
	}

	// sort param is accepted for future use; current queries use default ordering.
	_ = r.URL.Query().Get("sort")

	patternType := r.URL.Query().Get("type")
	project := r.URL.Query().Get("project")

	var patterns []*models.Pattern
	var err error

	if patternType != "" {
		// Filter by type
		patterns, err = store.GetPatternsByType(r.Context(), models.PatternType(patternType), limit)
	} else if project != "" {
		// Filter by project
		patterns, err = store.GetPatternsByProject(r.Context(), project, limit)
	} else {
		// Get all active patterns with offset support
		patterns, err = store.GetActivePatterns(r.Context(), limit+offset)
	}

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Apply offset (manual slice since GORM query uses Limit only)
	if offset > 0 && offset < len(patterns) {
		patterns = patterns[offset:]
	} else if offset >= len(patterns) {
		patterns = nil
	}
	// Re-apply limit after offset
	if len(patterns) > limit {
		patterns = patterns[:limit]
	}

	writeJSON(w, patterns)
}

// handleGetPatternStats godoc
// @Summary Get pattern statistics
// @Description Returns aggregate statistics about patterns including counts by type and status.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Success 200 {object} map[string]interface{}
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/stats [get]
func (s *Service) handleGetPatternStats(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	stats, err := store.GetPatternStats(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, stats)
}

// handleGetPatternByID godoc
// @Summary Get pattern by ID
// @Description Returns a single pattern by its ID.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Pattern ID"
// @Success 200 {object} models.Pattern
// @Failure 400 {string} string "invalid pattern ID"
// @Failure 404 {string} string "pattern not found"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/{id} [get]
func (s *Service) handleGetPatternByID(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid pattern ID", http.StatusBadRequest)
		return
	}

	pattern, err := store.GetPatternByID(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if pattern == nil {
		http.Error(w, "pattern not found", http.StatusNotFound)
		return
	}

	writeJSON(w, pattern)
}

// handleGetPatternInsight godoc
// @Summary Get pattern insight
// @Description Returns a formatted insight string for a pattern, generated by the pattern detector.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Pattern ID"
// @Success 200 {object} map[string]string
// @Failure 400 {string} string "invalid pattern ID"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern detector not initialized"
// @Router /api/patterns/{id}/insight [get]
func (s *Service) handleGetPatternInsight(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	detector := s.patternDetector
	s.initMu.RUnlock()

	if detector == nil {
		http.Error(w, "pattern detector not initialized", http.StatusServiceUnavailable)
		return
	}

	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid pattern ID", http.StatusBadRequest)
		return
	}

	insight, err := detector.GetPatternInsight(r.Context(), id)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, map[string]string{"insight": insight})
}

// handleDeletePattern godoc
// @Summary Delete pattern
// @Description Deletes a pattern by its ID.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Pattern ID"
// @Success 200 {object} map[string]string
// @Failure 400 {string} string "invalid pattern ID"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/{id} [delete]
func (s *Service) handleDeletePattern(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid pattern ID", http.StatusBadRequest)
		return
	}

	if err := store.DeletePattern(r.Context(), id); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, map[string]string{"status": "deleted"})
}

// handleDeprecatePattern godoc
// @Summary Deprecate pattern
// @Description Marks a pattern as deprecated.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param id path int true "Pattern ID"
// @Success 200 {object} map[string]string
// @Failure 400 {string} string "invalid pattern ID"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/{id}/deprecate [post]
func (s *Service) handleDeprecatePattern(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	idStr := chi.URLParam(r, "id")
	id, err := strconv.ParseInt(idStr, 10, 64)
	if err != nil {
		http.Error(w, "invalid pattern ID", http.StatusBadRequest)
		return
	}

	if err := store.MarkPatternDeprecated(r.Context(), id); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, map[string]string{"status": "deprecated"})
}

// MergePatternsRequest is the request body for merging patterns.
type MergePatternsRequest struct {
	SourceID int64 `json:"source_id"`
	TargetID int64 `json:"target_id"`
}

// handleSearchPatterns godoc
// @Summary Search patterns
// @Description Performs full-text search on patterns.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param q query string true "Search query"
// @Param limit query int false "Number of results (default 100)"
// @Success 200 {array} models.Pattern
// @Failure 400 {string} string "query parameter 'q' is required"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/search [get]
func (s *Service) handleSearchPatterns(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	query := r.URL.Query().Get("q")
	if query == "" {
		http.Error(w, "query parameter 'q' is required", http.StatusBadRequest)
		return
	}

	limit := DefaultPatternsLimit
	if l := r.URL.Query().Get("limit"); l != "" {
		if parsed, err := strconv.Atoi(l); err == nil && parsed > 0 {
			limit = parsed
		}
	}

	patterns, err := store.SearchPatternsFTS(r.Context(), query, limit)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, patterns)
}

// handleGetPatternByName godoc
// @Summary Get pattern by name
// @Description Returns a pattern by its unique name.
// @Tags Patterns
// @Produce json
// @Security ApiKeyAuth
// @Param name query string true "Pattern name"
// @Success 200 {object} models.Pattern
// @Failure 400 {string} string "query parameter 'name' is required"
// @Failure 404 {string} string "pattern not found"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/by-name [get]
func (s *Service) handleGetPatternByName(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	name := r.URL.Query().Get("name")
	if name == "" {
		http.Error(w, "query parameter 'name' is required", http.StatusBadRequest)
		return
	}

	pattern, err := store.GetPatternByName(r.Context(), name)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if pattern == nil {
		http.Error(w, "pattern not found", http.StatusNotFound)
		return
	}

	writeJSON(w, pattern)
}

// handleMergePatterns godoc
// @Summary Merge patterns
// @Description Merges a source pattern into a target pattern. Source pattern is consumed.
// @Tags Patterns
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param body body MergePatternsRequest true "Source and target pattern IDs"
// @Success 200 {object} map[string]string
// @Failure 400 {string} string "bad request"
// @Failure 500 {string} string "internal error"
// @Failure 503 {string} string "pattern store not initialized"
// @Router /api/patterns/merge [post]
func (s *Service) handleMergePatterns(w http.ResponseWriter, r *http.Request) {
	s.initMu.RLock()
	store := s.patternStore
	s.initMu.RUnlock()

	if store == nil {
		http.Error(w, "pattern store not initialized", http.StatusServiceUnavailable)
		return
	}

	var req MergePatternsRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if req.SourceID == 0 || req.TargetID == 0 {
		http.Error(w, "source_id and target_id are required", http.StatusBadRequest)
		return
	}

	if req.SourceID == req.TargetID {
		http.Error(w, "source_id and target_id cannot be the same", http.StatusBadRequest)
		return
	}

	if err := store.MergePatterns(r.Context(), req.SourceID, req.TargetID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	writeJSON(w, map[string]string{"status": "merged"})
}
